schema: https://api.kulturspektakel.de/graphql
documents:
  - ./app/**/*.tsx
generates:
  ./app/types/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
config:
  withMutationFn: true
  scalars:
    Date: string
    DateTime: string
hooks:
  afterOneFileWrite:
    - prettier --write
