// AUTO-GENERATED by `yarn sync:env`. Do not edit by hand —
// source of truth is scripts/sync-env.js (MANAGED_SECRETS + STATIC_ENV_VARS).

declare namespace NodeJS {
  interface ProcessEnv {
    AWS_ACCESS_KEY_ID: string;
    AWS_SECRET_ACCESS_KEY: string;
    CONTACTLESS_SALT: string;
    DATABASE_URL: string;
    FACEBOOK_ACCESS_TOKEN: string;
    GCP_LOCATION: string;
    GCP_PROJECT_ID: string;
    GCP_TASKS_QUEUE: string;
    GCP_TASKS_SCRAPER_QUEUE: string;
    GCP_TASKS_SERVICE_ACCOUNT_EMAIL: string;
    GCP_TASKS_SERVICE_ACCOUNT_KEY_JSON: string;
    GOOGLE_MAPS_API_KEY: string;
    GOOGLE_MAPS_API_KEY_SERVER: string;
    GOOGLE_SERVICE_ACCOUNT_EMAIL: string;
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: string;
    GOOGLE_SHEETS_KEY: string;
    SITE_URL: string;
    SLACK_BOT_TOKEN: string;
    SPOTIFY_CLIENT_ID: string;
    SPOTIFY_CLIENT_SECRET: string;
    STRIPE_API_KEY: string;
    STRIPE_SIGNING_SECRET: string;
    YOUTUBE_API_KEY: string;
  }
}
