// AUTO-GENERATED by `yarn sync:env`. Do not edit by hand —
// source of truth is the ENV_VARS manifest in scripts/sync-env.js.

declare namespace NodeJS {
  interface ProcessEnv {
    AWS_ACCESS_KEY_ID: string;
    AWS_SECRET_ACCESS_KEY: string;
    CONTACTLESS_SALT: string;
    DATABASE_URL: string;
    FACEBOOK_ACCESS_TOKEN: string;
    GCP_LOCATION: string;
    GCP_PROJECT_ID: string;
    GCP_TASKS_QUEUE: string;
    GCP_TASKS_SCRAPER_QUEUE: string;
    GCP_TASKS_SERVICE_ACCOUNT_EMAIL: string;
    GCP_TASKS_SERVICE_ACCOUNT_KEY_JSON: string;
    GOOGLE_MAPS_API_KEY: string;
    GOOGLE_MAPS_API_KEY_SERVER: string;
    GOOGLE_SERVICE_ACCOUNT_EMAIL: string;
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: string;
    GOOGLE_SHEETS_KEY: string;
    JWT_SECRET: string;
    NUCLINO_ANONYMOUS_PASSWORD: string;
    NUCLINO_API_KEY: string;
    NUCLINO_TEAM_ID: string;
    NUCLINO_WORKSPACE_ID: string;
    SAML_PRIVATE_KEY: string;
    SITE_URL: string;
    SLACK_BOT_TOKEN: string;
    SPOTIFY_CLIENT_ID: string;
    SPOTIFY_CLIENT_SECRET: string;
    STRIPE_API_KEY: string;
    STRIPE_SIGNING_SECRET: string;
    TWILIO_ACCOUNT_SID: string;
    TWILIO_API_KEY: string;
    TWILIO_API_SECRET: string;
    TWILIO_FROM_NUMBER: string;
    YOUTUBE_API_KEY: string;
  }
}
