// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: logmessage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { NoiseRecording } from "./noise";
import { Product } from "./product";

export const protobufPackage = "";

export interface LogMessage {
  deviceId: string;
  clientId: string;
  deviceTime: number;
  deviceTimeIsUtc: boolean;
  order?: LogMessage_Order | undefined;
  cardTransaction?: LogMessage_CardTransaction | undefined;
  batteryVoltage?: number | undefined;
  usbVoltage?: number | undefined;
  crewCardEnrollment?: LogMessage_CrewCardEnrollment | undefined;
  noiseRecording?: NoiseRecording | undefined;
}

export interface LogMessage_CardTransaction {
  transactionType: LogMessage_CardTransaction_TransactionType;
  balanceBefore: number;
  balanceAfter: number;
  depositBefore: number;
  depositAfter: number;
  cardId: string;
  counter?: number | undefined;
}

export enum LogMessage_CardTransaction_TransactionType {
  TOP_UP = 0,
  CHARGE = 1,
  CASHOUT = 2,
  REPAIR = 3,
  DONATION = 4,
  UNRECOGNIZED = -1,
}

export function logMessage_CardTransaction_TransactionTypeFromJSON(
  object: any,
): LogMessage_CardTransaction_TransactionType {
  switch (object) {
    case 0:
    case "TOP_UP":
      return LogMessage_CardTransaction_TransactionType.TOP_UP;
    case 1:
    case "CHARGE":
      return LogMessage_CardTransaction_TransactionType.CHARGE;
    case 2:
    case "CASHOUT":
      return LogMessage_CardTransaction_TransactionType.CASHOUT;
    case 3:
    case "REPAIR":
      return LogMessage_CardTransaction_TransactionType.REPAIR;
    case 4:
    case "DONATION":
      return LogMessage_CardTransaction_TransactionType.DONATION;
    case -1:
    case "UNRECOGNIZED":
    default:
      return LogMessage_CardTransaction_TransactionType.UNRECOGNIZED;
  }
}

export function logMessage_CardTransaction_TransactionTypeToJSON(
  object: LogMessage_CardTransaction_TransactionType,
): string {
  switch (object) {
    case LogMessage_CardTransaction_TransactionType.TOP_UP:
      return "TOP_UP";
    case LogMessage_CardTransaction_TransactionType.CHARGE:
      return "CHARGE";
    case LogMessage_CardTransaction_TransactionType.CASHOUT:
      return "CASHOUT";
    case LogMessage_CardTransaction_TransactionType.REPAIR:
      return "REPAIR";
    case LogMessage_CardTransaction_TransactionType.DONATION:
      return "DONATION";
    case LogMessage_CardTransaction_TransactionType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface LogMessage_Order {
  paymentMethod: LogMessage_Order_PaymentMethod;
  cartItems: LogMessage_Order_CartItem[];
  listId?: number | undefined;
  crewCardId?: Uint8Array | undefined;
}

export enum LogMessage_Order_PaymentMethod {
  CASH = 0,
  BON = 1,
  SUM_UP = 2,
  VOUCHER = 3,
  FREE_CREW = 4,
  FREE_BAND = 5,
  KULT_CARD = 6,
  UNRECOGNIZED = -1,
}

export function logMessage_Order_PaymentMethodFromJSON(object: any): LogMessage_Order_PaymentMethod {
  switch (object) {
    case 0:
    case "CASH":
      return LogMessage_Order_PaymentMethod.CASH;
    case 1:
    case "BON":
      return LogMessage_Order_PaymentMethod.BON;
    case 2:
    case "SUM_UP":
      return LogMessage_Order_PaymentMethod.SUM_UP;
    case 3:
    case "VOUCHER":
      return LogMessage_Order_PaymentMethod.VOUCHER;
    case 4:
    case "FREE_CREW":
      return LogMessage_Order_PaymentMethod.FREE_CREW;
    case 5:
    case "FREE_BAND":
      return LogMessage_Order_PaymentMethod.FREE_BAND;
    case 6:
    case "KULT_CARD":
      return LogMessage_Order_PaymentMethod.KULT_CARD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return LogMessage_Order_PaymentMethod.UNRECOGNIZED;
  }
}

export function logMessage_Order_PaymentMethodToJSON(object: LogMessage_Order_PaymentMethod): string {
  switch (object) {
    case LogMessage_Order_PaymentMethod.CASH:
      return "CASH";
    case LogMessage_Order_PaymentMethod.BON:
      return "BON";
    case LogMessage_Order_PaymentMethod.SUM_UP:
      return "SUM_UP";
    case LogMessage_Order_PaymentMethod.VOUCHER:
      return "VOUCHER";
    case LogMessage_Order_PaymentMethod.FREE_CREW:
      return "FREE_CREW";
    case LogMessage_Order_PaymentMethod.FREE_BAND:
      return "FREE_BAND";
    case LogMessage_Order_PaymentMethod.KULT_CARD:
      return "KULT_CARD";
    case LogMessage_Order_PaymentMethod.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface LogMessage_Order_CartItem {
  amount: number;
  product?: Product | undefined;
}

export interface LogMessage_CrewCardEnrollment {
  crewCardId: Uint8Array;
  validUntil: number;
}

function createBaseLogMessage(): LogMessage {
  return {
    deviceId: "",
    clientId: "",
    deviceTime: 0,
    deviceTimeIsUtc: false,
    order: undefined,
    cardTransaction: undefined,
    batteryVoltage: undefined,
    usbVoltage: undefined,
    crewCardEnrollment: undefined,
    noiseRecording: undefined,
  };
}

export const LogMessage: MessageFns<LogMessage> = {
  encode(message: LogMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceId !== "") {
      writer.uint32(10).string(message.deviceId);
    }
    if (message.clientId !== "") {
      writer.uint32(18).string(message.clientId);
    }
    if (message.deviceTime !== 0) {
      writer.uint32(24).int32(message.deviceTime);
    }
    if (message.deviceTimeIsUtc !== false) {
      writer.uint32(32).bool(message.deviceTimeIsUtc);
    }
    if (message.order !== undefined) {
      LogMessage_Order.encode(message.order, writer.uint32(42).fork()).join();
    }
    if (message.cardTransaction !== undefined) {
      LogMessage_CardTransaction.encode(message.cardTransaction, writer.uint32(50).fork()).join();
    }
    if (message.batteryVoltage !== undefined) {
      writer.uint32(56).int32(message.batteryVoltage);
    }
    if (message.usbVoltage !== undefined) {
      writer.uint32(64).int32(message.usbVoltage);
    }
    if (message.crewCardEnrollment !== undefined) {
      LogMessage_CrewCardEnrollment.encode(message.crewCardEnrollment, writer.uint32(82).fork()).join();
    }
    if (message.noiseRecording !== undefined) {
      NoiseRecording.encode(message.noiseRecording, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.deviceTime = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.deviceTimeIsUtc = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.order = LogMessage_Order.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.cardTransaction = LogMessage_CardTransaction.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.batteryVoltage = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.usbVoltage = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.crewCardEnrollment = LogMessage_CrewCardEnrollment.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.noiseRecording = NoiseRecording.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogMessage {
    return {
      deviceId: isSet(object.deviceId)
        ? globalThis.String(object.deviceId)
        : isSet(object.device_id)
        ? globalThis.String(object.device_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      deviceTime: isSet(object.deviceTime)
        ? globalThis.Number(object.deviceTime)
        : isSet(object.device_time)
        ? globalThis.Number(object.device_time)
        : 0,
      deviceTimeIsUtc: isSet(object.deviceTimeIsUtc)
        ? globalThis.Boolean(object.deviceTimeIsUtc)
        : isSet(object.device_time_is_utc)
        ? globalThis.Boolean(object.device_time_is_utc)
        : false,
      order: isSet(object.order) ? LogMessage_Order.fromJSON(object.order) : undefined,
      cardTransaction: isSet(object.cardTransaction)
        ? LogMessage_CardTransaction.fromJSON(object.cardTransaction)
        : isSet(object.card_transaction)
        ? LogMessage_CardTransaction.fromJSON(object.card_transaction)
        : undefined,
      batteryVoltage: isSet(object.batteryVoltage)
        ? globalThis.Number(object.batteryVoltage)
        : isSet(object.battery_voltage)
        ? globalThis.Number(object.battery_voltage)
        : undefined,
      usbVoltage: isSet(object.usbVoltage)
        ? globalThis.Number(object.usbVoltage)
        : isSet(object.usb_voltage)
        ? globalThis.Number(object.usb_voltage)
        : undefined,
      crewCardEnrollment: isSet(object.crewCardEnrollment)
        ? LogMessage_CrewCardEnrollment.fromJSON(object.crewCardEnrollment)
        : isSet(object.crew_card_enrollment)
        ? LogMessage_CrewCardEnrollment.fromJSON(object.crew_card_enrollment)
        : undefined,
      noiseRecording: isSet(object.noiseRecording)
        ? NoiseRecording.fromJSON(object.noiseRecording)
        : isSet(object.noise_recording)
        ? NoiseRecording.fromJSON(object.noise_recording)
        : undefined,
    };
  },

  toJSON(message: LogMessage): unknown {
    const obj: any = {};
    if (message.deviceId !== "") {
      obj.deviceId = message.deviceId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.deviceTime !== 0) {
      obj.deviceTime = Math.round(message.deviceTime);
    }
    if (message.deviceTimeIsUtc !== false) {
      obj.deviceTimeIsUtc = message.deviceTimeIsUtc;
    }
    if (message.order !== undefined) {
      obj.order = LogMessage_Order.toJSON(message.order);
    }
    if (message.cardTransaction !== undefined) {
      obj.cardTransaction = LogMessage_CardTransaction.toJSON(message.cardTransaction);
    }
    if (message.batteryVoltage !== undefined) {
      obj.batteryVoltage = Math.round(message.batteryVoltage);
    }
    if (message.usbVoltage !== undefined) {
      obj.usbVoltage = Math.round(message.usbVoltage);
    }
    if (message.crewCardEnrollment !== undefined) {
      obj.crewCardEnrollment = LogMessage_CrewCardEnrollment.toJSON(message.crewCardEnrollment);
    }
    if (message.noiseRecording !== undefined) {
      obj.noiseRecording = NoiseRecording.toJSON(message.noiseRecording);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogMessage>, I>>(base?: I): LogMessage {
    return LogMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogMessage>, I>>(object: I): LogMessage {
    const message = createBaseLogMessage();
    message.deviceId = object.deviceId ?? "";
    message.clientId = object.clientId ?? "";
    message.deviceTime = object.deviceTime ?? 0;
    message.deviceTimeIsUtc = object.deviceTimeIsUtc ?? false;
    message.order = (object.order !== undefined && object.order !== null)
      ? LogMessage_Order.fromPartial(object.order)
      : undefined;
    message.cardTransaction = (object.cardTransaction !== undefined && object.cardTransaction !== null)
      ? LogMessage_CardTransaction.fromPartial(object.cardTransaction)
      : undefined;
    message.batteryVoltage = object.batteryVoltage ?? undefined;
    message.usbVoltage = object.usbVoltage ?? undefined;
    message.crewCardEnrollment = (object.crewCardEnrollment !== undefined && object.crewCardEnrollment !== null)
      ? LogMessage_CrewCardEnrollment.fromPartial(object.crewCardEnrollment)
      : undefined;
    message.noiseRecording = (object.noiseRecording !== undefined && object.noiseRecording !== null)
      ? NoiseRecording.fromPartial(object.noiseRecording)
      : undefined;
    return message;
  },
};

function createBaseLogMessage_CardTransaction(): LogMessage_CardTransaction {
  return {
    transactionType: 0,
    balanceBefore: 0,
    balanceAfter: 0,
    depositBefore: 0,
    depositAfter: 0,
    cardId: "",
    counter: undefined,
  };
}

export const LogMessage_CardTransaction: MessageFns<LogMessage_CardTransaction> = {
  encode(message: LogMessage_CardTransaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transactionType !== 0) {
      writer.uint32(8).int32(message.transactionType);
    }
    if (message.balanceBefore !== 0) {
      writer.uint32(16).int32(message.balanceBefore);
    }
    if (message.balanceAfter !== 0) {
      writer.uint32(24).int32(message.balanceAfter);
    }
    if (message.depositBefore !== 0) {
      writer.uint32(32).int32(message.depositBefore);
    }
    if (message.depositAfter !== 0) {
      writer.uint32(40).int32(message.depositAfter);
    }
    if (message.cardId !== "") {
      writer.uint32(50).string(message.cardId);
    }
    if (message.counter !== undefined) {
      writer.uint32(56).int32(message.counter);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogMessage_CardTransaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogMessage_CardTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.transactionType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.balanceBefore = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.balanceAfter = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.depositBefore = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.depositAfter = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.cardId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.counter = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogMessage_CardTransaction {
    return {
      transactionType: isSet(object.transactionType)
        ? logMessage_CardTransaction_TransactionTypeFromJSON(object.transactionType)
        : isSet(object.transaction_type)
        ? logMessage_CardTransaction_TransactionTypeFromJSON(object.transaction_type)
        : 0,
      balanceBefore: isSet(object.balanceBefore)
        ? globalThis.Number(object.balanceBefore)
        : isSet(object.balance_before)
        ? globalThis.Number(object.balance_before)
        : 0,
      balanceAfter: isSet(object.balanceAfter)
        ? globalThis.Number(object.balanceAfter)
        : isSet(object.balance_after)
        ? globalThis.Number(object.balance_after)
        : 0,
      depositBefore: isSet(object.depositBefore)
        ? globalThis.Number(object.depositBefore)
        : isSet(object.deposit_before)
        ? globalThis.Number(object.deposit_before)
        : 0,
      depositAfter: isSet(object.depositAfter)
        ? globalThis.Number(object.depositAfter)
        : isSet(object.deposit_after)
        ? globalThis.Number(object.deposit_after)
        : 0,
      cardId: isSet(object.cardId)
        ? globalThis.String(object.cardId)
        : isSet(object.card_id)
        ? globalThis.String(object.card_id)
        : "",
      counter: isSet(object.counter) ? globalThis.Number(object.counter) : undefined,
    };
  },

  toJSON(message: LogMessage_CardTransaction): unknown {
    const obj: any = {};
    if (message.transactionType !== 0) {
      obj.transactionType = logMessage_CardTransaction_TransactionTypeToJSON(message.transactionType);
    }
    if (message.balanceBefore !== 0) {
      obj.balanceBefore = Math.round(message.balanceBefore);
    }
    if (message.balanceAfter !== 0) {
      obj.balanceAfter = Math.round(message.balanceAfter);
    }
    if (message.depositBefore !== 0) {
      obj.depositBefore = Math.round(message.depositBefore);
    }
    if (message.depositAfter !== 0) {
      obj.depositAfter = Math.round(message.depositAfter);
    }
    if (message.cardId !== "") {
      obj.cardId = message.cardId;
    }
    if (message.counter !== undefined) {
      obj.counter = Math.round(message.counter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogMessage_CardTransaction>, I>>(base?: I): LogMessage_CardTransaction {
    return LogMessage_CardTransaction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogMessage_CardTransaction>, I>>(object: I): LogMessage_CardTransaction {
    const message = createBaseLogMessage_CardTransaction();
    message.transactionType = object.transactionType ?? 0;
    message.balanceBefore = object.balanceBefore ?? 0;
    message.balanceAfter = object.balanceAfter ?? 0;
    message.depositBefore = object.depositBefore ?? 0;
    message.depositAfter = object.depositAfter ?? 0;
    message.cardId = object.cardId ?? "";
    message.counter = object.counter ?? undefined;
    return message;
  },
};

function createBaseLogMessage_Order(): LogMessage_Order {
  return { paymentMethod: 0, cartItems: [], listId: undefined, crewCardId: undefined };
}

export const LogMessage_Order: MessageFns<LogMessage_Order> = {
  encode(message: LogMessage_Order, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.paymentMethod !== 0) {
      writer.uint32(8).int32(message.paymentMethod);
    }
    for (const v of message.cartItems) {
      LogMessage_Order_CartItem.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.listId !== undefined) {
      writer.uint32(24).int32(message.listId);
    }
    if (message.crewCardId !== undefined) {
      writer.uint32(34).bytes(message.crewCardId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogMessage_Order {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogMessage_Order();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.paymentMethod = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cartItems.push(LogMessage_Order_CartItem.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.listId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.crewCardId = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogMessage_Order {
    return {
      paymentMethod: isSet(object.paymentMethod)
        ? logMessage_Order_PaymentMethodFromJSON(object.paymentMethod)
        : isSet(object.payment_method)
        ? logMessage_Order_PaymentMethodFromJSON(object.payment_method)
        : 0,
      cartItems: globalThis.Array.isArray(object?.cartItems)
        ? object.cartItems.map((e: any) => LogMessage_Order_CartItem.fromJSON(e))
        : globalThis.Array.isArray(object?.cart_items)
        ? object.cart_items.map((e: any) => LogMessage_Order_CartItem.fromJSON(e))
        : [],
      listId: isSet(object.listId)
        ? globalThis.Number(object.listId)
        : isSet(object.list_id)
        ? globalThis.Number(object.list_id)
        : undefined,
      crewCardId: isSet(object.crewCardId)
        ? bytesFromBase64(object.crewCardId)
        : isSet(object.crew_card_id)
        ? bytesFromBase64(object.crew_card_id)
        : undefined,
    };
  },

  toJSON(message: LogMessage_Order): unknown {
    const obj: any = {};
    if (message.paymentMethod !== 0) {
      obj.paymentMethod = logMessage_Order_PaymentMethodToJSON(message.paymentMethod);
    }
    if (message.cartItems?.length) {
      obj.cartItems = message.cartItems.map((e) => LogMessage_Order_CartItem.toJSON(e));
    }
    if (message.listId !== undefined) {
      obj.listId = Math.round(message.listId);
    }
    if (message.crewCardId !== undefined) {
      obj.crewCardId = base64FromBytes(message.crewCardId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogMessage_Order>, I>>(base?: I): LogMessage_Order {
    return LogMessage_Order.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogMessage_Order>, I>>(object: I): LogMessage_Order {
    const message = createBaseLogMessage_Order();
    message.paymentMethod = object.paymentMethod ?? 0;
    message.cartItems = object.cartItems?.map((e) => LogMessage_Order_CartItem.fromPartial(e)) || [];
    message.listId = object.listId ?? undefined;
    message.crewCardId = object.crewCardId ?? undefined;
    return message;
  },
};

function createBaseLogMessage_Order_CartItem(): LogMessage_Order_CartItem {
  return { amount: 0, product: undefined };
}

export const LogMessage_Order_CartItem: MessageFns<LogMessage_Order_CartItem> = {
  encode(message: LogMessage_Order_CartItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== 0) {
      writer.uint32(8).int32(message.amount);
    }
    if (message.product !== undefined) {
      Product.encode(message.product, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogMessage_Order_CartItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogMessage_Order_CartItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.amount = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.product = Product.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogMessage_Order_CartItem {
    return {
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      product: isSet(object.product) ? Product.fromJSON(object.product) : undefined,
    };
  },

  toJSON(message: LogMessage_Order_CartItem): unknown {
    const obj: any = {};
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.product !== undefined) {
      obj.product = Product.toJSON(message.product);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogMessage_Order_CartItem>, I>>(base?: I): LogMessage_Order_CartItem {
    return LogMessage_Order_CartItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogMessage_Order_CartItem>, I>>(object: I): LogMessage_Order_CartItem {
    const message = createBaseLogMessage_Order_CartItem();
    message.amount = object.amount ?? 0;
    message.product = (object.product !== undefined && object.product !== null)
      ? Product.fromPartial(object.product)
      : undefined;
    return message;
  },
};

function createBaseLogMessage_CrewCardEnrollment(): LogMessage_CrewCardEnrollment {
  return { crewCardId: new Uint8Array(0), validUntil: 0 };
}

export const LogMessage_CrewCardEnrollment: MessageFns<LogMessage_CrewCardEnrollment> = {
  encode(message: LogMessage_CrewCardEnrollment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.crewCardId.length !== 0) {
      writer.uint32(10).bytes(message.crewCardId);
    }
    if (message.validUntil !== 0) {
      writer.uint32(16).int32(message.validUntil);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogMessage_CrewCardEnrollment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogMessage_CrewCardEnrollment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.crewCardId = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.validUntil = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogMessage_CrewCardEnrollment {
    return {
      crewCardId: isSet(object.crewCardId)
        ? bytesFromBase64(object.crewCardId)
        : isSet(object.crew_card_id)
        ? bytesFromBase64(object.crew_card_id)
        : new Uint8Array(0),
      validUntil: isSet(object.validUntil)
        ? globalThis.Number(object.validUntil)
        : isSet(object.valid_until)
        ? globalThis.Number(object.valid_until)
        : 0,
    };
  },

  toJSON(message: LogMessage_CrewCardEnrollment): unknown {
    const obj: any = {};
    if (message.crewCardId.length !== 0) {
      obj.crewCardId = base64FromBytes(message.crewCardId);
    }
    if (message.validUntil !== 0) {
      obj.validUntil = Math.round(message.validUntil);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogMessage_CrewCardEnrollment>, I>>(base?: I): LogMessage_CrewCardEnrollment {
    return LogMessage_CrewCardEnrollment.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogMessage_CrewCardEnrollment>, I>>(
    object: I,
  ): LogMessage_CrewCardEnrollment {
    const message = createBaseLogMessage_CrewCardEnrollment();
    message.crewCardId = object.crewCardId ?? new Uint8Array(0);
    message.validUntil = object.validUntil ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
