// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.4
// source: noise.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

/**
 * One noise measurement over a fixed interval. Carried bare over MQTT
 * (noise/<id>/record) and BLE at ~1 Hz (record_interval_seconds = 1), and
 * wrapped in a LogMessage for the ~1/minute HTTP file upload as a 60-second
 * energy aggregate (record_interval_seconds = 60). Same fields and encoding
 * either way; only the span differs.
 */
export interface NoiseRecording {
  /** monotonic gap-detection counter. Per-second for live, per-minute for on-disk uploads — don't compare across the two streams. */
  seqNo: number;
  /** exactly 31 bytes, low → high 1/3-octave band; (dB - 20) * 2 per band */
  bands: Uint8Array;
  /** LAeq over the interval (same encoding as bands) */
  laeq: number;
  /** LCeq over the interval */
  lceq: number;
  /** LAFmax — max over the interval */
  lafmax: number;
  /** LCFmax — max over the interval */
  lcfmax: number;
  /** LCpeak — max over the interval */
  lcpeak: number;
  /** 1 = live 1 Hz sample, 60 = disk minute aggregate */
  recordIntervalSeconds: number;
  /** millivolts; live messages only, and only on battery */
  batteryMv?:
    | number
    | undefined;
  /** trailing 5-min LAeq; present only once populated */
  laeq5m?: number | undefined;
  lceq5m?:
    | number
    | undefined;
  /** trailing 30-min LAeq; present only once populated */
  laeq30m?: number | undefined;
  lceq30m?: number | undefined;
}

function createBaseNoiseRecording(): NoiseRecording {
  return {
    seqNo: 0,
    bands: new Uint8Array(0),
    laeq: 0,
    lceq: 0,
    lafmax: 0,
    lcfmax: 0,
    lcpeak: 0,
    recordIntervalSeconds: 0,
    batteryMv: undefined,
    laeq5m: undefined,
    lceq5m: undefined,
    laeq30m: undefined,
    lceq30m: undefined,
  };
}

export const NoiseRecording: MessageFns<NoiseRecording> = {
  encode(message: NoiseRecording, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seqNo !== 0) {
      writer.uint32(8).uint32(message.seqNo);
    }
    if (message.bands.length !== 0) {
      writer.uint32(18).bytes(message.bands);
    }
    if (message.laeq !== 0) {
      writer.uint32(24).uint32(message.laeq);
    }
    if (message.lceq !== 0) {
      writer.uint32(32).uint32(message.lceq);
    }
    if (message.lafmax !== 0) {
      writer.uint32(40).uint32(message.lafmax);
    }
    if (message.lcfmax !== 0) {
      writer.uint32(48).uint32(message.lcfmax);
    }
    if (message.lcpeak !== 0) {
      writer.uint32(56).uint32(message.lcpeak);
    }
    if (message.recordIntervalSeconds !== 0) {
      writer.uint32(64).uint32(message.recordIntervalSeconds);
    }
    if (message.batteryMv !== undefined) {
      writer.uint32(72).uint32(message.batteryMv);
    }
    if (message.laeq5m !== undefined) {
      writer.uint32(80).uint32(message.laeq5m);
    }
    if (message.lceq5m !== undefined) {
      writer.uint32(88).uint32(message.lceq5m);
    }
    if (message.laeq30m !== undefined) {
      writer.uint32(96).uint32(message.laeq30m);
    }
    if (message.lceq30m !== undefined) {
      writer.uint32(104).uint32(message.lceq30m);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NoiseRecording {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNoiseRecording();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seqNo = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bands = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.laeq = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.lceq = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.lafmax = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.lcfmax = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.lcpeak = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.recordIntervalSeconds = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.batteryMv = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.laeq5m = reader.uint32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.lceq5m = reader.uint32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.laeq30m = reader.uint32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.lceq30m = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NoiseRecording {
    return {
      seqNo: isSet(object.seqNo)
        ? globalThis.Number(object.seqNo)
        : isSet(object.seq_no)
        ? globalThis.Number(object.seq_no)
        : 0,
      bands: isSet(object.bands) ? bytesFromBase64(object.bands) : new Uint8Array(0),
      laeq: isSet(object.laeq) ? globalThis.Number(object.laeq) : 0,
      lceq: isSet(object.lceq) ? globalThis.Number(object.lceq) : 0,
      lafmax: isSet(object.lafmax) ? globalThis.Number(object.lafmax) : 0,
      lcfmax: isSet(object.lcfmax) ? globalThis.Number(object.lcfmax) : 0,
      lcpeak: isSet(object.lcpeak) ? globalThis.Number(object.lcpeak) : 0,
      recordIntervalSeconds: isSet(object.recordIntervalSeconds)
        ? globalThis.Number(object.recordIntervalSeconds)
        : isSet(object.record_interval_seconds)
        ? globalThis.Number(object.record_interval_seconds)
        : 0,
      batteryMv: isSet(object.batteryMv)
        ? globalThis.Number(object.batteryMv)
        : isSet(object.battery_mv)
        ? globalThis.Number(object.battery_mv)
        : undefined,
      laeq5m: isSet(object.laeq5m)
        ? globalThis.Number(object.laeq5m)
        : isSet(object.laeq_5m)
        ? globalThis.Number(object.laeq_5m)
        : undefined,
      lceq5m: isSet(object.lceq5m)
        ? globalThis.Number(object.lceq5m)
        : isSet(object.lceq_5m)
        ? globalThis.Number(object.lceq_5m)
        : undefined,
      laeq30m: isSet(object.laeq30m)
        ? globalThis.Number(object.laeq30m)
        : isSet(object.laeq_30m)
        ? globalThis.Number(object.laeq_30m)
        : undefined,
      lceq30m: isSet(object.lceq30m)
        ? globalThis.Number(object.lceq30m)
        : isSet(object.lceq_30m)
        ? globalThis.Number(object.lceq_30m)
        : undefined,
    };
  },

  toJSON(message: NoiseRecording): unknown {
    const obj: any = {};
    if (message.seqNo !== 0) {
      obj.seqNo = Math.round(message.seqNo);
    }
    if (message.bands.length !== 0) {
      obj.bands = base64FromBytes(message.bands);
    }
    if (message.laeq !== 0) {
      obj.laeq = Math.round(message.laeq);
    }
    if (message.lceq !== 0) {
      obj.lceq = Math.round(message.lceq);
    }
    if (message.lafmax !== 0) {
      obj.lafmax = Math.round(message.lafmax);
    }
    if (message.lcfmax !== 0) {
      obj.lcfmax = Math.round(message.lcfmax);
    }
    if (message.lcpeak !== 0) {
      obj.lcpeak = Math.round(message.lcpeak);
    }
    if (message.recordIntervalSeconds !== 0) {
      obj.recordIntervalSeconds = Math.round(message.recordIntervalSeconds);
    }
    if (message.batteryMv !== undefined) {
      obj.batteryMv = Math.round(message.batteryMv);
    }
    if (message.laeq5m !== undefined) {
      obj.laeq5m = Math.round(message.laeq5m);
    }
    if (message.lceq5m !== undefined) {
      obj.lceq5m = Math.round(message.lceq5m);
    }
    if (message.laeq30m !== undefined) {
      obj.laeq30m = Math.round(message.laeq30m);
    }
    if (message.lceq30m !== undefined) {
      obj.lceq30m = Math.round(message.lceq30m);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NoiseRecording>, I>>(base?: I): NoiseRecording {
    return NoiseRecording.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NoiseRecording>, I>>(object: I): NoiseRecording {
    const message = createBaseNoiseRecording();
    message.seqNo = object.seqNo ?? 0;
    message.bands = object.bands ?? new Uint8Array(0);
    message.laeq = object.laeq ?? 0;
    message.lceq = object.lceq ?? 0;
    message.lafmax = object.lafmax ?? 0;
    message.lcfmax = object.lcfmax ?? 0;
    message.lcpeak = object.lcpeak ?? 0;
    message.recordIntervalSeconds = object.recordIntervalSeconds ?? 0;
    message.batteryMv = object.batteryMv ?? undefined;
    message.laeq5m = object.laeq5m ?? undefined;
    message.lceq5m = object.lceq5m ?? undefined;
    message.laeq30m = object.laeq30m ?? undefined;
    message.lceq30m = object.lceq30m ?? undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
