// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.4
// source: noise.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface NoiseRecording {
  /** 1 (MQTT/BLE live) or up to 300 (file) */
  records: NoiseRecording_Record[];
  /** sliding-window LAeq over last 15 min, */
  laeq15m: number;
  /** same encoding as Record.laeq_1s (= (dB - 20) * 2) */
  lceq15m: number;
  /** battery voltage in millivolts; only set for */
  batteryMv?: number | undefined;
}

export interface NoiseRecording_Record {
  /** monotonic; gap detection */
  seqNo: number;
  /** 31 bytes; (dB - 20) * 2 per band */
  bands: Uint8Array;
  /** same encoding as bands */
  laeq1s: number;
  lceq1s: number;
  lafmax1s: number;
  lcfmax1s: number;
  lcpeak1s: number;
}

function createBaseNoiseRecording(): NoiseRecording {
  return { records: [], laeq15m: 0, lceq15m: 0, batteryMv: undefined };
}

export const NoiseRecording: MessageFns<NoiseRecording> = {
  encode(message: NoiseRecording, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.records) {
      NoiseRecording_Record.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.laeq15m !== 0) {
      writer.uint32(24).uint32(message.laeq15m);
    }
    if (message.lceq15m !== 0) {
      writer.uint32(32).uint32(message.lceq15m);
    }
    if (message.batteryMv !== undefined) {
      writer.uint32(40).uint32(message.batteryMv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NoiseRecording {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNoiseRecording();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.records.push(NoiseRecording_Record.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.laeq15m = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.lceq15m = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.batteryMv = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NoiseRecording {
    return {
      records: globalThis.Array.isArray(object?.records)
        ? object.records.map((e: any) => NoiseRecording_Record.fromJSON(e))
        : [],
      laeq15m: isSet(object.laeq15m)
        ? globalThis.Number(object.laeq15m)
        : isSet(object.laeq_15m)
        ? globalThis.Number(object.laeq_15m)
        : 0,
      lceq15m: isSet(object.lceq15m)
        ? globalThis.Number(object.lceq15m)
        : isSet(object.lceq_15m)
        ? globalThis.Number(object.lceq_15m)
        : 0,
      batteryMv: isSet(object.batteryMv)
        ? globalThis.Number(object.batteryMv)
        : isSet(object.battery_mv)
        ? globalThis.Number(object.battery_mv)
        : undefined,
    };
  },

  toJSON(message: NoiseRecording): unknown {
    const obj: any = {};
    if (message.records?.length) {
      obj.records = message.records.map((e) => NoiseRecording_Record.toJSON(e));
    }
    if (message.laeq15m !== 0) {
      obj.laeq15m = Math.round(message.laeq15m);
    }
    if (message.lceq15m !== 0) {
      obj.lceq15m = Math.round(message.lceq15m);
    }
    if (message.batteryMv !== undefined) {
      obj.batteryMv = Math.round(message.batteryMv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NoiseRecording>, I>>(base?: I): NoiseRecording {
    return NoiseRecording.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NoiseRecording>, I>>(object: I): NoiseRecording {
    const message = createBaseNoiseRecording();
    message.records = object.records?.map((e) => NoiseRecording_Record.fromPartial(e)) || [];
    message.laeq15m = object.laeq15m ?? 0;
    message.lceq15m = object.lceq15m ?? 0;
    message.batteryMv = object.batteryMv ?? undefined;
    return message;
  },
};

function createBaseNoiseRecording_Record(): NoiseRecording_Record {
  return { seqNo: 0, bands: new Uint8Array(0), laeq1s: 0, lceq1s: 0, lafmax1s: 0, lcfmax1s: 0, lcpeak1s: 0 };
}

export const NoiseRecording_Record: MessageFns<NoiseRecording_Record> = {
  encode(message: NoiseRecording_Record, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seqNo !== 0) {
      writer.uint32(8).uint32(message.seqNo);
    }
    if (message.bands.length !== 0) {
      writer.uint32(18).bytes(message.bands);
    }
    if (message.laeq1s !== 0) {
      writer.uint32(24).uint32(message.laeq1s);
    }
    if (message.lceq1s !== 0) {
      writer.uint32(32).uint32(message.lceq1s);
    }
    if (message.lafmax1s !== 0) {
      writer.uint32(40).uint32(message.lafmax1s);
    }
    if (message.lcfmax1s !== 0) {
      writer.uint32(48).uint32(message.lcfmax1s);
    }
    if (message.lcpeak1s !== 0) {
      writer.uint32(56).uint32(message.lcpeak1s);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NoiseRecording_Record {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNoiseRecording_Record();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seqNo = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bands = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.laeq1s = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.lceq1s = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.lafmax1s = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.lcfmax1s = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.lcpeak1s = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NoiseRecording_Record {
    return {
      seqNo: isSet(object.seqNo)
        ? globalThis.Number(object.seqNo)
        : isSet(object.seq_no)
        ? globalThis.Number(object.seq_no)
        : 0,
      bands: isSet(object.bands) ? bytesFromBase64(object.bands) : new Uint8Array(0),
      laeq1s: isSet(object.laeq1s)
        ? globalThis.Number(object.laeq1s)
        : isSet(object.laeq_1s)
        ? globalThis.Number(object.laeq_1s)
        : 0,
      lceq1s: isSet(object.lceq1s)
        ? globalThis.Number(object.lceq1s)
        : isSet(object.lceq_1s)
        ? globalThis.Number(object.lceq_1s)
        : 0,
      lafmax1s: isSet(object.lafmax1s)
        ? globalThis.Number(object.lafmax1s)
        : isSet(object.lafmax_1s)
        ? globalThis.Number(object.lafmax_1s)
        : 0,
      lcfmax1s: isSet(object.lcfmax1s)
        ? globalThis.Number(object.lcfmax1s)
        : isSet(object.lcfmax_1s)
        ? globalThis.Number(object.lcfmax_1s)
        : 0,
      lcpeak1s: isSet(object.lcpeak1s)
        ? globalThis.Number(object.lcpeak1s)
        : isSet(object.lcpeak_1s)
        ? globalThis.Number(object.lcpeak_1s)
        : 0,
    };
  },

  toJSON(message: NoiseRecording_Record): unknown {
    const obj: any = {};
    if (message.seqNo !== 0) {
      obj.seqNo = Math.round(message.seqNo);
    }
    if (message.bands.length !== 0) {
      obj.bands = base64FromBytes(message.bands);
    }
    if (message.laeq1s !== 0) {
      obj.laeq1s = Math.round(message.laeq1s);
    }
    if (message.lceq1s !== 0) {
      obj.lceq1s = Math.round(message.lceq1s);
    }
    if (message.lafmax1s !== 0) {
      obj.lafmax1s = Math.round(message.lafmax1s);
    }
    if (message.lcfmax1s !== 0) {
      obj.lcfmax1s = Math.round(message.lcfmax1s);
    }
    if (message.lcpeak1s !== 0) {
      obj.lcpeak1s = Math.round(message.lcpeak1s);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NoiseRecording_Record>, I>>(base?: I): NoiseRecording_Record {
    return NoiseRecording_Record.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NoiseRecording_Record>, I>>(object: I): NoiseRecording_Record {
    const message = createBaseNoiseRecording_Record();
    message.seqNo = object.seqNo ?? 0;
    message.bands = object.bands ?? new Uint8Array(0);
    message.laeq1s = object.laeq1s ?? 0;
    message.lceq1s = object.lceq1s ?? 0;
    message.lafmax1s = object.lafmax1s ?? 0;
    message.lcfmax1s = object.lcfmax1s ?? 0;
    message.lcpeak1s = object.lcpeak1s ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
