// AUTO-GENERATED by `yarn sync:env`. Do not edit by hand —
// source of truth is scripts/sync-env.js (MANAGED_SECRETS + STATIC_ENV_VARS).

function required(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required env var: ${name}`);
  }
  return value;
}

export const env = {
  get AWS_ACCESS_KEY_ID() { return required('AWS_ACCESS_KEY_ID'); },
  get AWS_SECRET_ACCESS_KEY() { return required('AWS_SECRET_ACCESS_KEY'); },
  get CONTACTLESS_SALT() { return required('CONTACTLESS_SALT'); },
  get DATABASE_URL() { return required('DATABASE_URL'); },
  get GCP_LOCATION() { return required('GCP_LOCATION'); },
  get GCP_PROJECT_ID() { return required('GCP_PROJECT_ID'); },
  get GCP_TASKS_QUEUE() { return required('GCP_TASKS_QUEUE'); },
  get GCP_TASKS_SERVICE_ACCOUNT_EMAIL() { return required('GCP_TASKS_SERVICE_ACCOUNT_EMAIL'); },
  get GCP_TASKS_SERVICE_ACCOUNT_KEY_JSON() { return required('GCP_TASKS_SERVICE_ACCOUNT_KEY_JSON'); },
  get GOOGLE_MAPS_API_KEY() { return required('GOOGLE_MAPS_API_KEY'); },
  get GOOGLE_MAPS_API_KEY_SERVER() { return required('GOOGLE_MAPS_API_KEY_SERVER'); },
  get GOOGLE_SERVICE_ACCOUNT_EMAIL() { return required('GOOGLE_SERVICE_ACCOUNT_EMAIL'); },
  get GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY() { return required('GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY'); },
  get GOOGLE_SHEETS_KEY() { return required('GOOGLE_SHEETS_KEY'); },
  get SITE_URL() { return required('SITE_URL'); },
  get SLACK_BOT_TOKEN() { return required('SLACK_BOT_TOKEN'); },
  get SPOTIFY_CLIENT_ID() { return required('SPOTIFY_CLIENT_ID'); },
  get SPOTIFY_CLIENT_SECRET() { return required('SPOTIFY_CLIENT_SECRET'); },
  get STRIPE_API_KEY() { return required('STRIPE_API_KEY'); },
};
