#!/usr/bin/env python3
"""Generate .env + src/utils/env.server.ts from `terraform output -json`.

Run after `terraform apply`. Pass `--vercel` to also push every var to the
Vercel project (Production + Development; preview is skipped — see the
vercel CLI limitation we hit elsewhere).

Source of truth: `local.env_vars` in terraform/main.tf. Adding a new var
means editing that map; everything downstream regenerates from there.
"""
import argparse
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TERRAFORM_DIR = ROOT / "terraform"
ENV_FILE = ROOT / ".env"
ENV_MODULE = ROOT / "src" / "utils" / "env.server.ts"


def load_env_vars() -> dict[str, str]:
    raw = subprocess.check_output(
        ["terraform", f"-chdir={TERRAFORM_DIR}", "output", "-json"]
    )
    return json.loads(raw)["env_vars"]["value"]


def render_env(env_vars: dict[str, str]) -> str:
    """Render the .env file. Auto-generated banner first; one var per line.

    Multi-line values (PEM keys) go in double quotes — dotenv supports those.
    The SA-key JSON is single-quoted (preserves its `\\n` escapes intact).
    """
    lines = [
        "# AUTO-GENERATED by `yarn sync:env`. Do not edit by hand —",
        "# source of truth is terraform/main.tf (local.env_vars).",
        "",
    ]
    for name in sorted(env_vars):
        value = env_vars[name]
        if name == "GCP_TASKS_SERVICE_ACCOUNT_KEY_JSON":
            compact = json.dumps(json.loads(value), separators=(",", ":"))
            lines.append(f"{name}='{compact}'")
        else:
            lines.append(f'{name}="{value}"')
    return "\n".join(lines) + "\n"


def render_module(names: list[str]) -> str:
    """Render src/utils/env.server.ts with one typed getter per env var."""
    lines = [
        "// AUTO-GENERATED by `yarn sync:env`. Do not edit by hand —",
        "// source of truth is terraform/main.tf (local.env_vars).",
        "",
        "function required(name: string): string {",
        "  const value = process.env[name];",
        "  if (!value) {",
        "    throw new Error(`Missing required env var: ${name}`);",
        "  }",
        "  return value;",
        "}",
        "",
        "export const env = {",
    ]
    for name in sorted(names):
        lines.append(f"  get {name}() {{ return required('{name}'); }},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def push_to_vercel(env_vars: dict[str, str]) -> None:
    """Idempotently push every var to Vercel for production + development.

    Preview is skipped — Vercel CLI 50.x rejects the "all preview branches"
    add in non-interactive mode (see commit b0211e7).
    """
    vercel = [str(ROOT / "node_modules" / ".bin" / "vercel")]
    for name in sorted(env_vars):
        value = env_vars[name]
        for environment in ("production", "development"):
            subprocess.run(
                vercel + ["env", "rm", name, environment, "--yes"],
                capture_output=True,
                text=True,
                timeout=60,
            )
            result = subprocess.run(
                vercel + ["env", "add", name, environment],
                input=value,
                text=True,
                capture_output=True,
                timeout=60,
            )
            ok = "OK  " if result.returncode == 0 else "FAIL"
            print(f"{ok} {name:<40} {environment}", flush=True)
            if result.returncode != 0:
                print(f"      stderr: {result.stderr.strip()[-200:]}", flush=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--vercel",
        action="store_true",
        help="Also push every var to Vercel (production + development).",
    )
    args = parser.parse_args()

    env_vars = load_env_vars()

    ENV_FILE.write_text(render_env(env_vars))
    print(f"wrote {ENV_FILE.relative_to(ROOT)} ({len(env_vars)} vars)")

    ENV_MODULE.write_text(render_module(list(env_vars.keys())))
    print(f"wrote {ENV_MODULE.relative_to(ROOT)}")

    if args.vercel:
        print("pushing to Vercel (this takes ~30s)...")
        push_to_vercel(env_vars)

    return 0


if __name__ == "__main__":
    sys.exit(main())
