#!/usr/bin/env node
/**
 * Generate .env + src/utils/env.server.ts from Google Secret Manager.
 *
 * Pass `--vercel` to also push every var to the Vercel project (Production
 * + Development; preview is skipped — see the Vercel CLI non-interactive
 * limitation we hit elsewhere).
 *
 * Auth: ADC. Locally that's `gcloud auth application-default login`; in CI
 * it's whatever `google-github-actions/auth` set up via the GCP_SA_KEY
 * GitHub Actions secret.
 *
 * Where the env vars come from:
 *   - Static config (project id, site url, etc.) — `STATIC_ENV_VARS` below.
 *     These rarely change; keep this in sync with terraform's locals + the
 *     hardcoded values in production.tf (tasks-invoker SA name, "default"
 *     queue, region).
 *   - Secret Manager — `MANAGED_SECRETS` below. Some of these are real
 *     external secrets (created via `gcloud secrets create`); some are
 *     mirrors of terraform-managed values (Maps API key strings, SA key
 *     JSON). Either way: same lookup pattern.
 */
import {SecretManagerServiceClient} from '@google-cloud/secret-manager';
import {spawnSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENV_FILE = resolve(ROOT, '.env');
const ENV_MODULE = resolve(ROOT, 'src/utils/env.server.ts');
const VERCEL = resolve(ROOT, 'node_modules/.bin/vercel');

const GCP_PROJECT_ID = 'gmail-reminder-api';

const STATIC_ENV_VARS = {
  GCP_PROJECT_ID,
  SITE_URL: 'https://www.kulturspektakel.de',
  GCP_LOCATION: 'europe-west1',
  GCP_TASKS_QUEUE: 'default',
  GCP_TASKS_SERVICE_ACCOUNT_EMAIL: `tasks-invoker@${GCP_PROJECT_ID}.iam.gserviceaccount.com`,
};

const MANAGED_SECRETS = [
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'CONTACTLESS_SALT',
  'DATABASE_URL',
  'GCP_TASKS_SERVICE_ACCOUNT_KEY_JSON',
  'GOOGLE_MAPS_API_KEY',
  'GOOGLE_MAPS_API_KEY_SERVER',
  'GOOGLE_SERVICE_ACCOUNT_EMAIL',
  'GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY',
  'SLACK_BOT_TOKEN',
  'SPOTIFY_CLIENT_ID',
  'SPOTIFY_CLIENT_SECRET',
  'STRIPE_API_KEY',
];

async function loadEnvVars() {
  const client = new SecretManagerServiceClient();
  const fetched = await Promise.all(
    MANAGED_SECRETS.map(async (name) => {
      const [version] = await client.accessSecretVersion({
        name: `projects/${GCP_PROJECT_ID}/secrets/${name}/versions/latest`,
      });
      const data = version.payload?.data;
      if (!data) {
        throw new Error(`Empty value for secret ${name}`);
      }
      return [name, Buffer.from(data).toString('utf-8')];
    }),
  );
  return {...STATIC_ENV_VARS, ...Object.fromEntries(fetched)};
}

function renderEnv(envVars) {
  const lines = [
    '# AUTO-GENERATED by `yarn sync:env`. Do not edit by hand —',
    '# source of truth is Secret Manager (tools/sync-env.js).',
    '',
  ];
  for (const name of Object.keys(envVars).sort()) {
    const value = envVars[name];
    if (name === 'GCP_TASKS_SERVICE_ACCOUNT_KEY_JSON') {
      // Compact-JSON single-line, single-quoted so the `\n` escapes inside
      // private_key survive dotenv parsing.
      const compact = JSON.stringify(JSON.parse(value));
      lines.push(`${name}='${compact}'`);
    } else {
      lines.push(`${name}="${value}"`);
    }
  }
  return lines.join('\n') + '\n';
}

function renderModule(names) {
  const lines = [
    '// AUTO-GENERATED by `yarn sync:env`. Do not edit by hand —',
    '// source of truth is tools/sync-env.js (MANAGED_SECRETS + STATIC_ENV_VARS).',
    '',
    'function required(name: string): string {',
    '  const value = process.env[name];',
    '  if (!value) {',
    '    throw new Error(`Missing required env var: ${name}`);',
    '  }',
    '  return value;',
    '}',
    '',
    'export const env = {',
  ];
  for (const name of [...names].sort()) {
    lines.push(`  get ${name}() { return required('${name}'); },`);
  }
  lines.push('};');
  return lines.join('\n') + '\n';
}

function pushToVercel(envVars) {
  for (const name of Object.keys(envVars).sort()) {
    const value = envVars[name];
    for (const environment of ['production', 'development']) {
      spawnSync(VERCEL, ['env', 'rm', name, environment, '--yes'], {
        encoding: 'utf-8',
        timeout: 60_000,
      });
      const result = spawnSync(VERCEL, ['env', 'add', name, environment], {
        input: value,
        encoding: 'utf-8',
        timeout: 60_000,
      });
      const ok = result.status === 0;
      console.log(
        `${ok ? 'OK  ' : 'FAIL'} ${name.padEnd(40)} ${environment}`,
      );
      if (!ok) {
        console.log(`      stderr: ${(result.stderr ?? '').trim().slice(-200)}`);
      }
    }
  }
}

const envVars = await loadEnvVars();

writeFileSync(ENV_FILE, renderEnv(envVars));
console.log(`wrote .env (${Object.keys(envVars).length} vars)`);

writeFileSync(ENV_MODULE, renderModule(Object.keys(envVars)));
console.log('wrote src/utils/env.server.ts');

if (process.argv.includes('--vercel')) {
  console.log('pushing to Vercel (this takes ~30s)...');
  pushToVercel(envVars);
}
