#!/usr/bin/env node
/**
 * Generate .env + src/utils/env.server.ts from `terraform output -json`.
 *
 * Run after `terraform apply`. Pass `--vercel` to also push every var to
 * the Vercel project (Production + Development; preview is skipped — see
 * the Vercel CLI non-interactive limitation we hit elsewhere).
 *
 * Source of truth: `local.env_vars` in terraform/main.tf. Adding a new var
 * means editing that map; everything downstream regenerates from there.
 */
import {execFileSync, spawnSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TERRAFORM_DIR = resolve(ROOT, 'terraform');
const ENV_FILE = resolve(ROOT, '.env');
const ENV_MODULE = resolve(ROOT, 'src/utils/env.server.ts');
const VERCEL = resolve(ROOT, 'node_modules/.bin/vercel');

function loadEnvVars() {
  const raw = execFileSync(
    'terraform',
    [`-chdir=${TERRAFORM_DIR}`, 'output', '-json'],
    {encoding: 'utf-8'},
  );
  return JSON.parse(raw).env_vars.value;
}

function renderEnv(envVars) {
  // Multi-line PEMs go in double quotes (dotenv supports those).
  // The SA-key JSON is single-quoted so the literal `\n` escapes inside
  // its private_key field don't get re-interpreted by dotenv.
  const lines = [
    '# AUTO-GENERATED by `yarn sync:env`. Do not edit by hand —',
    '# source of truth is terraform/main.tf (local.env_vars).',
    '',
  ];
  for (const name of Object.keys(envVars).sort()) {
    const value = envVars[name];
    if (name === 'GCP_TASKS_SERVICE_ACCOUNT_KEY_JSON') {
      const compact = JSON.stringify(JSON.parse(value));
      lines.push(`${name}='${compact}'`);
    } else {
      lines.push(`${name}="${value}"`);
    }
  }
  return lines.join('\n') + '\n';
}

function renderModule(names) {
  const lines = [
    '// AUTO-GENERATED by `yarn sync:env`. Do not edit by hand —',
    '// source of truth is terraform/main.tf (local.env_vars).',
    '',
    'function required(name: string): string {',
    '  const value = process.env[name];',
    '  if (!value) {',
    '    throw new Error(`Missing required env var: ${name}`);',
    '  }',
    '  return value;',
    '}',
    '',
    'export const env = {',
  ];
  for (const name of [...names].sort()) {
    lines.push(`  get ${name}() { return required('${name}'); },`);
  }
  lines.push('};');
  return lines.join('\n') + '\n';
}

function pushToVercel(envVars) {
  for (const name of Object.keys(envVars).sort()) {
    const value = envVars[name];
    for (const environment of ['production', 'development']) {
      spawnSync(VERCEL, ['env', 'rm', name, environment, '--yes'], {
        encoding: 'utf-8',
        timeout: 60_000,
      });
      const result = spawnSync(VERCEL, ['env', 'add', name, environment], {
        input: value,
        encoding: 'utf-8',
        timeout: 60_000,
      });
      const ok = result.status === 0;
      console.log(
        `${ok ? 'OK  ' : 'FAIL'} ${name.padEnd(40)} ${environment}`,
      );
      if (!ok) {
        console.log(`      stderr: ${(result.stderr ?? '').trim().slice(-200)}`);
      }
    }
  }
}

const envVars = loadEnvVars();

writeFileSync(ENV_FILE, renderEnv(envVars));
console.log(`wrote .env (${Object.keys(envVars).length} vars)`);

writeFileSync(ENV_MODULE, renderModule(Object.keys(envVars)));
console.log('wrote src/utils/env.server.ts');

if (process.argv.includes('--vercel')) {
  console.log('pushing to Vercel (this takes ~30s)...');
  pushToVercel(envVars);
}
