/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as MainRouteImport } from './routes/_main'
import { Route as CrewIndexRouteImport } from './routes/crew.index'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as SamlLogoutRouteImport } from './routes/saml.logout'
import { Route as SamlLoginRouteImport } from './routes/saml.login'
import { Route as CrewLautstaerkeRouteImport } from './routes/crew.lautstaerke'
import { Route as MainSpeisekarteRouteImport } from './routes/_main.speisekarte'
import { Route as MainPlakateRouteImport } from './routes/_main.plakate'
import { Route as MainNuclinoSsoRouteImport } from './routes/_main.nuclino-sso'
import { Route as MainMitgliedsantragRouteImport } from './routes/_main.mitgliedsantrag'
import { Route as MainLogoRouteImport } from './routes/_main.logo'
import { Route as MainLineupRouteImport } from './routes/_main.lineup'
import { Route as MainLearnRouteImport } from './routes/_main.learn'
import { Route as MainInfosRouteImport } from './routes/_main.infos'
import { Route as MainEventsRouteImport } from './routes/_main.events'
import { Route as MainBookingRouteImport } from './routes/_main.booking'
import { Route as MainBadgesRouteImport } from './routes/_main.badges'
import { Route as MainAngebotRouteImport } from './routes/_main.angebot'
import { Route as MainRouteRouteImport } from './routes/_main.Route'
import { Route as MainSlugRouteImport } from './routes/_main.$slug'
import { Route as CrewLautstaerkeIndexRouteImport } from './routes/crew.lautstaerke.index'
import { Route as MainLineupIndexRouteImport } from './routes/_main.lineup.index'
import { Route as CrewLautstaerkeDeviceRouteImport } from './routes/crew.lautstaerke.$device'
import { Route as ApiTasksSpotifyListenersRouteImport } from './routes/api.tasks.spotify-listeners'
import { Route as ApiTasksSendEmailRouteImport } from './routes/api.tasks.send-email'
import { Route as ApiTasksNonceRequestInvalidateRouteImport } from './routes/api.tasks.nonce-request-invalidate'
import { Route as ApiTasksNonceInvalidateRouteImport } from './routes/api.tasks.nonce-invalidate'
import { Route as ApiTasksInstagramFollowerRouteImport } from './routes/api.tasks.instagram-follower'
import { Route as ApiTasksGmailWatchRefreshRouteImport } from './routes/api.tasks.gmail-watch-refresh'
import { Route as ApiTasksGmailReminderRouteImport } from './routes/api.tasks.gmail-reminder'
import { Route as ApiTasksGmailNotificationRouteImport } from './routes/api.tasks.gmail-notification'
import { Route as ApiTasksFacebookLikesRouteImport } from './routes/api.tasks.facebook-likes'
import { Route as ApiTasksCrewCardEnrolledRouteImport } from './routes/api.tasks.crew-card-enrolled'
import { Route as ApiTasksCreateNonceRequestRouteImport } from './routes/api.tasks.create-nonce-request'
import { Route as ApiTasksCreateMembershipApplicationRouteImport } from './routes/api.tasks.create-membership-application'
import { Route as ApiTasksCreateBandApplicationRouteImport } from './routes/api.tasks.create-band-application'
import { Route as ApiTasksBandApplicationDistanceRouteImport } from './routes/api.tasks.band-application-distance'
import { Route as ApiTasksBandApplicationDemoRouteImport } from './routes/api.tasks.band-application-demo'
import { Route as ApiTasksBadgeAwardedRouteImport } from './routes/api.tasks.badge-awarded'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiNoiseLogRouteImport } from './routes/api.noise.log'
import { Route as ApiKultcashLogRouteImport } from './routes/api.kultcash.log'
import { Route as ApiKultcashListsRouteImport } from './routes/api.kultcash.lists'
import { Route as ApiKultcashConfigRouteImport } from './routes/api.kultcash.config'
import { Route as MainNewsArchivRouteImport } from './routes/_main.news.archiv'
import { Route as MainNewsSlugRouteImport } from './routes/_main.news.$slug'
import { Route as MainMitgliedsantragDankeRouteImport } from './routes/_main.mitgliedsantrag_.danke'
import { Route as MainLineupYearRouteImport } from './routes/_main.lineup.$year'
import { Route as MainEventsIdRouteImport } from './routes/_main.events_.$id'
import { Route as MainCardHashRouteImport } from './routes/_main.card.$hash'
import { Route as MainBookingApplicationTypeRouteImport } from './routes/_main.booking_.$applicationType'
import { Route as ApiSpendenQuittungIdRouteImport } from './routes/api.spenden.quittung.$id'
import { Route as MainSpendenQuittungIdRouteImport } from './routes/_main.spenden_.quittung.$id'
import { Route as MainLineupYearSlugRouteImport } from './routes/_main.lineup.$year_.$slug'
import { Route as MainCardHashKultRouteImport } from './routes/_main.card.$hash.kult'
import { Route as MainCardHashCrewRouteImport } from './routes/_main.card.$hash.crew'
import { Route as MainBookingApplicationTypeDankeRouteImport } from './routes/_main.booking_.$applicationType_.danke'

const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIndexRoute = CrewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrewRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const SamlLogoutRoute = SamlLogoutRouteImport.update({
  id: '/saml/logout',
  path: '/saml/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const SamlLoginRoute = SamlLoginRouteImport.update({
  id: '/saml/login',
  path: '/saml/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewLautstaerkeRoute = CrewLautstaerkeRouteImport.update({
  id: '/lautstaerke',
  path: '/lautstaerke',
  getParentRoute: () => CrewRoute,
} as any)
const MainSpeisekarteRoute = MainSpeisekarteRouteImport.update({
  id: '/speisekarte',
  path: '/speisekarte',
  getParentRoute: () => MainRoute,
} as any)
const MainPlakateRoute = MainPlakateRouteImport.update({
  id: '/plakate',
  path: '/plakate',
  getParentRoute: () => MainRoute,
} as any)
const MainNuclinoSsoRoute = MainNuclinoSsoRouteImport.update({
  id: '/nuclino-sso',
  path: '/nuclino-sso',
  getParentRoute: () => MainRoute,
} as any)
const MainMitgliedsantragRoute = MainMitgliedsantragRouteImport.update({
  id: '/mitgliedsantrag',
  path: '/mitgliedsantrag',
  getParentRoute: () => MainRoute,
} as any)
const MainLogoRoute = MainLogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => MainRoute,
} as any)
const MainLineupRoute = MainLineupRouteImport.update({
  id: '/lineup',
  path: '/lineup',
  getParentRoute: () => MainRoute,
} as any)
const MainLearnRoute = MainLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => MainRoute,
} as any)
const MainInfosRoute = MainInfosRouteImport.update({
  id: '/infos',
  path: '/infos',
  getParentRoute: () => MainRoute,
} as any)
const MainEventsRoute = MainEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => MainRoute,
} as any)
const MainBookingRoute = MainBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => MainRoute,
} as any)
const MainBadgesRoute = MainBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => MainRoute,
} as any)
const MainAngebotRoute = MainAngebotRouteImport.update({
  id: '/angebot',
  path: '/angebot',
  getParentRoute: () => MainRoute,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/Route',
  path: '/Route',
  getParentRoute: () => MainRoute,
} as any)
const MainSlugRoute = MainSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MainRoute,
} as any)
const CrewLautstaerkeIndexRoute = CrewLautstaerkeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrewLautstaerkeRoute,
} as any)
const MainLineupIndexRoute = MainLineupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLineupRoute,
} as any)
const CrewLautstaerkeDeviceRoute = CrewLautstaerkeDeviceRouteImport.update({
  id: '/$device',
  path: '/$device',
  getParentRoute: () => CrewLautstaerkeRoute,
} as any)
const ApiTasksSpotifyListenersRoute =
  ApiTasksSpotifyListenersRouteImport.update({
    id: '/api/tasks/spotify-listeners',
    path: '/api/tasks/spotify-listeners',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksSendEmailRoute = ApiTasksSendEmailRouteImport.update({
  id: '/api/tasks/send-email',
  path: '/api/tasks/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksNonceRequestInvalidateRoute =
  ApiTasksNonceRequestInvalidateRouteImport.update({
    id: '/api/tasks/nonce-request-invalidate',
    path: '/api/tasks/nonce-request-invalidate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksNonceInvalidateRoute = ApiTasksNonceInvalidateRouteImport.update({
  id: '/api/tasks/nonce-invalidate',
  path: '/api/tasks/nonce-invalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksInstagramFollowerRoute =
  ApiTasksInstagramFollowerRouteImport.update({
    id: '/api/tasks/instagram-follower',
    path: '/api/tasks/instagram-follower',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksGmailWatchRefreshRoute =
  ApiTasksGmailWatchRefreshRouteImport.update({
    id: '/api/tasks/gmail-watch-refresh',
    path: '/api/tasks/gmail-watch-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksGmailReminderRoute = ApiTasksGmailReminderRouteImport.update({
  id: '/api/tasks/gmail-reminder',
  path: '/api/tasks/gmail-reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksGmailNotificationRoute =
  ApiTasksGmailNotificationRouteImport.update({
    id: '/api/tasks/gmail-notification',
    path: '/api/tasks/gmail-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksFacebookLikesRoute = ApiTasksFacebookLikesRouteImport.update({
  id: '/api/tasks/facebook-likes',
  path: '/api/tasks/facebook-likes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksCrewCardEnrolledRoute =
  ApiTasksCrewCardEnrolledRouteImport.update({
    id: '/api/tasks/crew-card-enrolled',
    path: '/api/tasks/crew-card-enrolled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksCreateNonceRequestRoute =
  ApiTasksCreateNonceRequestRouteImport.update({
    id: '/api/tasks/create-nonce-request',
    path: '/api/tasks/create-nonce-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksCreateMembershipApplicationRoute =
  ApiTasksCreateMembershipApplicationRouteImport.update({
    id: '/api/tasks/create-membership-application',
    path: '/api/tasks/create-membership-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksCreateBandApplicationRoute =
  ApiTasksCreateBandApplicationRouteImport.update({
    id: '/api/tasks/create-band-application',
    path: '/api/tasks/create-band-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksBandApplicationDistanceRoute =
  ApiTasksBandApplicationDistanceRouteImport.update({
    id: '/api/tasks/band-application-distance',
    path: '/api/tasks/band-application-distance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksBandApplicationDemoRoute =
  ApiTasksBandApplicationDemoRouteImport.update({
    id: '/api/tasks/band-application-demo',
    path: '/api/tasks/band-application-demo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksBadgeAwardedRoute = ApiTasksBadgeAwardedRouteImport.update({
  id: '/api/tasks/badge-awarded',
  path: '/api/tasks/badge-awarded',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNoiseLogRoute = ApiNoiseLogRouteImport.update({
  id: '/api/noise/log',
  path: '/api/noise/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKultcashLogRoute = ApiKultcashLogRouteImport.update({
  id: '/api/kultcash/log',
  path: '/api/kultcash/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKultcashListsRoute = ApiKultcashListsRouteImport.update({
  id: '/api/kultcash/lists',
  path: '/api/kultcash/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKultcashConfigRoute = ApiKultcashConfigRouteImport.update({
  id: '/api/kultcash/config',
  path: '/api/kultcash/config',
  getParentRoute: () => rootRouteImport,
} as any)
const MainNewsArchivRoute = MainNewsArchivRouteImport.update({
  id: '/news/archiv',
  path: '/news/archiv',
  getParentRoute: () => MainRoute,
} as any)
const MainNewsSlugRoute = MainNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => MainRoute,
} as any)
const MainMitgliedsantragDankeRoute =
  MainMitgliedsantragDankeRouteImport.update({
    id: '/mitgliedsantrag_/danke',
    path: '/mitgliedsantrag/danke',
    getParentRoute: () => MainRoute,
  } as any)
const MainLineupYearRoute = MainLineupYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => MainLineupRoute,
} as any)
const MainEventsIdRoute = MainEventsIdRouteImport.update({
  id: '/events_/$id',
  path: '/events/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainCardHashRoute = MainCardHashRouteImport.update({
  id: '/card/$hash',
  path: '/card/$hash',
  getParentRoute: () => MainRoute,
} as any)
const MainBookingApplicationTypeRoute =
  MainBookingApplicationTypeRouteImport.update({
    id: '/booking_/$applicationType',
    path: '/booking/$applicationType',
    getParentRoute: () => MainRoute,
  } as any)
const ApiSpendenQuittungIdRoute = ApiSpendenQuittungIdRouteImport.update({
  id: '/api/spenden/quittung/$id',
  path: '/api/spenden/quittung/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSpendenQuittungIdRoute = MainSpendenQuittungIdRouteImport.update({
  id: '/spenden_/quittung/$id',
  path: '/spenden/quittung/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainLineupYearSlugRoute = MainLineupYearSlugRouteImport.update({
  id: '/$year_/$slug',
  path: '/$year/$slug',
  getParentRoute: () => MainLineupRoute,
} as any)
const MainCardHashKultRoute = MainCardHashKultRouteImport.update({
  id: '/kult',
  path: '/kult',
  getParentRoute: () => MainCardHashRoute,
} as any)
const MainCardHashCrewRoute = MainCardHashCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => MainCardHashRoute,
} as any)
const MainBookingApplicationTypeDankeRoute =
  MainBookingApplicationTypeDankeRouteImport.update({
    id: '/booking_/$applicationType_/danke',
    path: '/booking/$applicationType/danke',
    getParentRoute: () => MainRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/crew': typeof CrewRouteWithChildren
  '/$slug': typeof MainSlugRoute
  '/Route': typeof MainRouteRoute
  '/angebot': typeof MainAngebotRoute
  '/badges': typeof MainBadgesRoute
  '/booking': typeof MainBookingRoute
  '/events': typeof MainEventsRoute
  '/infos': typeof MainInfosRoute
  '/learn': typeof MainLearnRoute
  '/lineup': typeof MainLineupRouteWithChildren
  '/logo': typeof MainLogoRoute
  '/mitgliedsantrag': typeof MainMitgliedsantragRoute
  '/nuclino-sso': typeof MainNuclinoSsoRoute
  '/plakate': typeof MainPlakateRoute
  '/speisekarte': typeof MainSpeisekarteRoute
  '/crew/lautstaerke': typeof CrewLautstaerkeRouteWithChildren
  '/saml/login': typeof SamlLoginRoute
  '/saml/logout': typeof SamlLogoutRoute
  '/crew/': typeof CrewIndexRoute
  '/booking/$applicationType': typeof MainBookingApplicationTypeRoute
  '/card/$hash': typeof MainCardHashRouteWithChildren
  '/events/$id': typeof MainEventsIdRoute
  '/lineup/$year': typeof MainLineupYearRoute
  '/mitgliedsantrag/danke': typeof MainMitgliedsantragDankeRoute
  '/news/$slug': typeof MainNewsSlugRoute
  '/news/archiv': typeof MainNewsArchivRoute
  '/api/kultcash/config': typeof ApiKultcashConfigRoute
  '/api/kultcash/lists': typeof ApiKultcashListsRoute
  '/api/kultcash/log': typeof ApiKultcashLogRoute
  '/api/noise/log': typeof ApiNoiseLogRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/tasks/badge-awarded': typeof ApiTasksBadgeAwardedRoute
  '/api/tasks/band-application-demo': typeof ApiTasksBandApplicationDemoRoute
  '/api/tasks/band-application-distance': typeof ApiTasksBandApplicationDistanceRoute
  '/api/tasks/create-band-application': typeof ApiTasksCreateBandApplicationRoute
  '/api/tasks/create-membership-application': typeof ApiTasksCreateMembershipApplicationRoute
  '/api/tasks/create-nonce-request': typeof ApiTasksCreateNonceRequestRoute
  '/api/tasks/crew-card-enrolled': typeof ApiTasksCrewCardEnrolledRoute
  '/api/tasks/facebook-likes': typeof ApiTasksFacebookLikesRoute
  '/api/tasks/gmail-notification': typeof ApiTasksGmailNotificationRoute
  '/api/tasks/gmail-reminder': typeof ApiTasksGmailReminderRoute
  '/api/tasks/gmail-watch-refresh': typeof ApiTasksGmailWatchRefreshRoute
  '/api/tasks/instagram-follower': typeof ApiTasksInstagramFollowerRoute
  '/api/tasks/nonce-invalidate': typeof ApiTasksNonceInvalidateRoute
  '/api/tasks/nonce-request-invalidate': typeof ApiTasksNonceRequestInvalidateRoute
  '/api/tasks/send-email': typeof ApiTasksSendEmailRoute
  '/api/tasks/spotify-listeners': typeof ApiTasksSpotifyListenersRoute
  '/crew/lautstaerke/$device': typeof CrewLautstaerkeDeviceRoute
  '/lineup/': typeof MainLineupIndexRoute
  '/crew/lautstaerke/': typeof CrewLautstaerkeIndexRoute
  '/booking/$applicationType/danke': typeof MainBookingApplicationTypeDankeRoute
  '/card/$hash/crew': typeof MainCardHashCrewRoute
  '/card/$hash/kult': typeof MainCardHashKultRoute
  '/lineup/$year/$slug': typeof MainLineupYearSlugRoute
  '/spenden/quittung/$id': typeof MainSpendenQuittungIdRoute
  '/api/spenden/quittung/$id': typeof ApiSpendenQuittungIdRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof MainSlugRoute
  '/Route': typeof MainRouteRoute
  '/angebot': typeof MainAngebotRoute
  '/badges': typeof MainBadgesRoute
  '/booking': typeof MainBookingRoute
  '/events': typeof MainEventsRoute
  '/infos': typeof MainInfosRoute
  '/learn': typeof MainLearnRoute
  '/logo': typeof MainLogoRoute
  '/mitgliedsantrag': typeof MainMitgliedsantragRoute
  '/nuclino-sso': typeof MainNuclinoSsoRoute
  '/plakate': typeof MainPlakateRoute
  '/speisekarte': typeof MainSpeisekarteRoute
  '/saml/login': typeof SamlLoginRoute
  '/saml/logout': typeof SamlLogoutRoute
  '/': typeof MainIndexRoute
  '/crew': typeof CrewIndexRoute
  '/booking/$applicationType': typeof MainBookingApplicationTypeRoute
  '/card/$hash': typeof MainCardHashRouteWithChildren
  '/events/$id': typeof MainEventsIdRoute
  '/lineup/$year': typeof MainLineupYearRoute
  '/mitgliedsantrag/danke': typeof MainMitgliedsantragDankeRoute
  '/news/$slug': typeof MainNewsSlugRoute
  '/news/archiv': typeof MainNewsArchivRoute
  '/api/kultcash/config': typeof ApiKultcashConfigRoute
  '/api/kultcash/lists': typeof ApiKultcashListsRoute
  '/api/kultcash/log': typeof ApiKultcashLogRoute
  '/api/noise/log': typeof ApiNoiseLogRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/tasks/badge-awarded': typeof ApiTasksBadgeAwardedRoute
  '/api/tasks/band-application-demo': typeof ApiTasksBandApplicationDemoRoute
  '/api/tasks/band-application-distance': typeof ApiTasksBandApplicationDistanceRoute
  '/api/tasks/create-band-application': typeof ApiTasksCreateBandApplicationRoute
  '/api/tasks/create-membership-application': typeof ApiTasksCreateMembershipApplicationRoute
  '/api/tasks/create-nonce-request': typeof ApiTasksCreateNonceRequestRoute
  '/api/tasks/crew-card-enrolled': typeof ApiTasksCrewCardEnrolledRoute
  '/api/tasks/facebook-likes': typeof ApiTasksFacebookLikesRoute
  '/api/tasks/gmail-notification': typeof ApiTasksGmailNotificationRoute
  '/api/tasks/gmail-reminder': typeof ApiTasksGmailReminderRoute
  '/api/tasks/gmail-watch-refresh': typeof ApiTasksGmailWatchRefreshRoute
  '/api/tasks/instagram-follower': typeof ApiTasksInstagramFollowerRoute
  '/api/tasks/nonce-invalidate': typeof ApiTasksNonceInvalidateRoute
  '/api/tasks/nonce-request-invalidate': typeof ApiTasksNonceRequestInvalidateRoute
  '/api/tasks/send-email': typeof ApiTasksSendEmailRoute
  '/api/tasks/spotify-listeners': typeof ApiTasksSpotifyListenersRoute
  '/crew/lautstaerke/$device': typeof CrewLautstaerkeDeviceRoute
  '/lineup': typeof MainLineupIndexRoute
  '/crew/lautstaerke': typeof CrewLautstaerkeIndexRoute
  '/booking/$applicationType/danke': typeof MainBookingApplicationTypeDankeRoute
  '/card/$hash/crew': typeof MainCardHashCrewRoute
  '/card/$hash/kult': typeof MainCardHashKultRoute
  '/lineup/$year/$slug': typeof MainLineupYearSlugRoute
  '/spenden/quittung/$id': typeof MainSpendenQuittungIdRoute
  '/api/spenden/quittung/$id': typeof ApiSpendenQuittungIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/crew': typeof CrewRouteWithChildren
  '/_main/$slug': typeof MainSlugRoute
  '/_main/Route': typeof MainRouteRoute
  '/_main/angebot': typeof MainAngebotRoute
  '/_main/badges': typeof MainBadgesRoute
  '/_main/booking': typeof MainBookingRoute
  '/_main/events': typeof MainEventsRoute
  '/_main/infos': typeof MainInfosRoute
  '/_main/learn': typeof MainLearnRoute
  '/_main/lineup': typeof MainLineupRouteWithChildren
  '/_main/logo': typeof MainLogoRoute
  '/_main/mitgliedsantrag': typeof MainMitgliedsantragRoute
  '/_main/nuclino-sso': typeof MainNuclinoSsoRoute
  '/_main/plakate': typeof MainPlakateRoute
  '/_main/speisekarte': typeof MainSpeisekarteRoute
  '/crew/lautstaerke': typeof CrewLautstaerkeRouteWithChildren
  '/saml/login': typeof SamlLoginRoute
  '/saml/logout': typeof SamlLogoutRoute
  '/_main/': typeof MainIndexRoute
  '/crew/': typeof CrewIndexRoute
  '/_main/booking_/$applicationType': typeof MainBookingApplicationTypeRoute
  '/_main/card/$hash': typeof MainCardHashRouteWithChildren
  '/_main/events_/$id': typeof MainEventsIdRoute
  '/_main/lineup/$year': typeof MainLineupYearRoute
  '/_main/mitgliedsantrag_/danke': typeof MainMitgliedsantragDankeRoute
  '/_main/news/$slug': typeof MainNewsSlugRoute
  '/_main/news/archiv': typeof MainNewsArchivRoute
  '/api/kultcash/config': typeof ApiKultcashConfigRoute
  '/api/kultcash/lists': typeof ApiKultcashListsRoute
  '/api/kultcash/log': typeof ApiKultcashLogRoute
  '/api/noise/log': typeof ApiNoiseLogRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/tasks/badge-awarded': typeof ApiTasksBadgeAwardedRoute
  '/api/tasks/band-application-demo': typeof ApiTasksBandApplicationDemoRoute
  '/api/tasks/band-application-distance': typeof ApiTasksBandApplicationDistanceRoute
  '/api/tasks/create-band-application': typeof ApiTasksCreateBandApplicationRoute
  '/api/tasks/create-membership-application': typeof ApiTasksCreateMembershipApplicationRoute
  '/api/tasks/create-nonce-request': typeof ApiTasksCreateNonceRequestRoute
  '/api/tasks/crew-card-enrolled': typeof ApiTasksCrewCardEnrolledRoute
  '/api/tasks/facebook-likes': typeof ApiTasksFacebookLikesRoute
  '/api/tasks/gmail-notification': typeof ApiTasksGmailNotificationRoute
  '/api/tasks/gmail-reminder': typeof ApiTasksGmailReminderRoute
  '/api/tasks/gmail-watch-refresh': typeof ApiTasksGmailWatchRefreshRoute
  '/api/tasks/instagram-follower': typeof ApiTasksInstagramFollowerRoute
  '/api/tasks/nonce-invalidate': typeof ApiTasksNonceInvalidateRoute
  '/api/tasks/nonce-request-invalidate': typeof ApiTasksNonceRequestInvalidateRoute
  '/api/tasks/send-email': typeof ApiTasksSendEmailRoute
  '/api/tasks/spotify-listeners': typeof ApiTasksSpotifyListenersRoute
  '/crew/lautstaerke/$device': typeof CrewLautstaerkeDeviceRoute
  '/_main/lineup/': typeof MainLineupIndexRoute
  '/crew/lautstaerke/': typeof CrewLautstaerkeIndexRoute
  '/_main/booking_/$applicationType_/danke': typeof MainBookingApplicationTypeDankeRoute
  '/_main/card/$hash/crew': typeof MainCardHashCrewRoute
  '/_main/card/$hash/kult': typeof MainCardHashKultRoute
  '/_main/lineup/$year_/$slug': typeof MainLineupYearSlugRoute
  '/_main/spenden_/quittung/$id': typeof MainSpendenQuittungIdRoute
  '/api/spenden/quittung/$id': typeof ApiSpendenQuittungIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crew'
    | '/$slug'
    | '/Route'
    | '/angebot'
    | '/badges'
    | '/booking'
    | '/events'
    | '/infos'
    | '/learn'
    | '/lineup'
    | '/logo'
    | '/mitgliedsantrag'
    | '/nuclino-sso'
    | '/plakate'
    | '/speisekarte'
    | '/crew/lautstaerke'
    | '/saml/login'
    | '/saml/logout'
    | '/crew/'
    | '/booking/$applicationType'
    | '/card/$hash'
    | '/events/$id'
    | '/lineup/$year'
    | '/mitgliedsantrag/danke'
    | '/news/$slug'
    | '/news/archiv'
    | '/api/kultcash/config'
    | '/api/kultcash/lists'
    | '/api/kultcash/log'
    | '/api/noise/log'
    | '/api/stripe/webhook'
    | '/api/tasks/badge-awarded'
    | '/api/tasks/band-application-demo'
    | '/api/tasks/band-application-distance'
    | '/api/tasks/create-band-application'
    | '/api/tasks/create-membership-application'
    | '/api/tasks/create-nonce-request'
    | '/api/tasks/crew-card-enrolled'
    | '/api/tasks/facebook-likes'
    | '/api/tasks/gmail-notification'
    | '/api/tasks/gmail-reminder'
    | '/api/tasks/gmail-watch-refresh'
    | '/api/tasks/instagram-follower'
    | '/api/tasks/nonce-invalidate'
    | '/api/tasks/nonce-request-invalidate'
    | '/api/tasks/send-email'
    | '/api/tasks/spotify-listeners'
    | '/crew/lautstaerke/$device'
    | '/lineup/'
    | '/crew/lautstaerke/'
    | '/booking/$applicationType/danke'
    | '/card/$hash/crew'
    | '/card/$hash/kult'
    | '/lineup/$year/$slug'
    | '/spenden/quittung/$id'
    | '/api/spenden/quittung/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/Route'
    | '/angebot'
    | '/badges'
    | '/booking'
    | '/events'
    | '/infos'
    | '/learn'
    | '/logo'
    | '/mitgliedsantrag'
    | '/nuclino-sso'
    | '/plakate'
    | '/speisekarte'
    | '/saml/login'
    | '/saml/logout'
    | '/'
    | '/crew'
    | '/booking/$applicationType'
    | '/card/$hash'
    | '/events/$id'
    | '/lineup/$year'
    | '/mitgliedsantrag/danke'
    | '/news/$slug'
    | '/news/archiv'
    | '/api/kultcash/config'
    | '/api/kultcash/lists'
    | '/api/kultcash/log'
    | '/api/noise/log'
    | '/api/stripe/webhook'
    | '/api/tasks/badge-awarded'
    | '/api/tasks/band-application-demo'
    | '/api/tasks/band-application-distance'
    | '/api/tasks/create-band-application'
    | '/api/tasks/create-membership-application'
    | '/api/tasks/create-nonce-request'
    | '/api/tasks/crew-card-enrolled'
    | '/api/tasks/facebook-likes'
    | '/api/tasks/gmail-notification'
    | '/api/tasks/gmail-reminder'
    | '/api/tasks/gmail-watch-refresh'
    | '/api/tasks/instagram-follower'
    | '/api/tasks/nonce-invalidate'
    | '/api/tasks/nonce-request-invalidate'
    | '/api/tasks/send-email'
    | '/api/tasks/spotify-listeners'
    | '/crew/lautstaerke/$device'
    | '/lineup'
    | '/crew/lautstaerke'
    | '/booking/$applicationType/danke'
    | '/card/$hash/crew'
    | '/card/$hash/kult'
    | '/lineup/$year/$slug'
    | '/spenden/quittung/$id'
    | '/api/spenden/quittung/$id'
  id:
    | '__root__'
    | '/_main'
    | '/crew'
    | '/_main/$slug'
    | '/_main/Route'
    | '/_main/angebot'
    | '/_main/badges'
    | '/_main/booking'
    | '/_main/events'
    | '/_main/infos'
    | '/_main/learn'
    | '/_main/lineup'
    | '/_main/logo'
    | '/_main/mitgliedsantrag'
    | '/_main/nuclino-sso'
    | '/_main/plakate'
    | '/_main/speisekarte'
    | '/crew/lautstaerke'
    | '/saml/login'
    | '/saml/logout'
    | '/_main/'
    | '/crew/'
    | '/_main/booking_/$applicationType'
    | '/_main/card/$hash'
    | '/_main/events_/$id'
    | '/_main/lineup/$year'
    | '/_main/mitgliedsantrag_/danke'
    | '/_main/news/$slug'
    | '/_main/news/archiv'
    | '/api/kultcash/config'
    | '/api/kultcash/lists'
    | '/api/kultcash/log'
    | '/api/noise/log'
    | '/api/stripe/webhook'
    | '/api/tasks/badge-awarded'
    | '/api/tasks/band-application-demo'
    | '/api/tasks/band-application-distance'
    | '/api/tasks/create-band-application'
    | '/api/tasks/create-membership-application'
    | '/api/tasks/create-nonce-request'
    | '/api/tasks/crew-card-enrolled'
    | '/api/tasks/facebook-likes'
    | '/api/tasks/gmail-notification'
    | '/api/tasks/gmail-reminder'
    | '/api/tasks/gmail-watch-refresh'
    | '/api/tasks/instagram-follower'
    | '/api/tasks/nonce-invalidate'
    | '/api/tasks/nonce-request-invalidate'
    | '/api/tasks/send-email'
    | '/api/tasks/spotify-listeners'
    | '/crew/lautstaerke/$device'
    | '/_main/lineup/'
    | '/crew/lautstaerke/'
    | '/_main/booking_/$applicationType_/danke'
    | '/_main/card/$hash/crew'
    | '/_main/card/$hash/kult'
    | '/_main/lineup/$year_/$slug'
    | '/_main/spenden_/quittung/$id'
    | '/api/spenden/quittung/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  CrewRoute: typeof CrewRouteWithChildren
  SamlLoginRoute: typeof SamlLoginRoute
  SamlLogoutRoute: typeof SamlLogoutRoute
  ApiKultcashConfigRoute: typeof ApiKultcashConfigRoute
  ApiKultcashListsRoute: typeof ApiKultcashListsRoute
  ApiKultcashLogRoute: typeof ApiKultcashLogRoute
  ApiNoiseLogRoute: typeof ApiNoiseLogRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTasksBadgeAwardedRoute: typeof ApiTasksBadgeAwardedRoute
  ApiTasksBandApplicationDemoRoute: typeof ApiTasksBandApplicationDemoRoute
  ApiTasksBandApplicationDistanceRoute: typeof ApiTasksBandApplicationDistanceRoute
  ApiTasksCreateBandApplicationRoute: typeof ApiTasksCreateBandApplicationRoute
  ApiTasksCreateMembershipApplicationRoute: typeof ApiTasksCreateMembershipApplicationRoute
  ApiTasksCreateNonceRequestRoute: typeof ApiTasksCreateNonceRequestRoute
  ApiTasksCrewCardEnrolledRoute: typeof ApiTasksCrewCardEnrolledRoute
  ApiTasksFacebookLikesRoute: typeof ApiTasksFacebookLikesRoute
  ApiTasksGmailNotificationRoute: typeof ApiTasksGmailNotificationRoute
  ApiTasksGmailReminderRoute: typeof ApiTasksGmailReminderRoute
  ApiTasksGmailWatchRefreshRoute: typeof ApiTasksGmailWatchRefreshRoute
  ApiTasksInstagramFollowerRoute: typeof ApiTasksInstagramFollowerRoute
  ApiTasksNonceInvalidateRoute: typeof ApiTasksNonceInvalidateRoute
  ApiTasksNonceRequestInvalidateRoute: typeof ApiTasksNonceRequestInvalidateRoute
  ApiTasksSendEmailRoute: typeof ApiTasksSendEmailRoute
  ApiTasksSpotifyListenersRoute: typeof ApiTasksSpotifyListenersRoute
  ApiSpendenQuittungIdRoute: typeof ApiSpendenQuittungIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/': {
      id: '/crew/'
      path: '/'
      fullPath: '/crew/'
      preLoaderRoute: typeof CrewIndexRouteImport
      parentRoute: typeof CrewRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/saml/logout': {
      id: '/saml/logout'
      path: '/saml/logout'
      fullPath: '/saml/logout'
      preLoaderRoute: typeof SamlLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saml/login': {
      id: '/saml/login'
      path: '/saml/login'
      fullPath: '/saml/login'
      preLoaderRoute: typeof SamlLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/lautstaerke': {
      id: '/crew/lautstaerke'
      path: '/lautstaerke'
      fullPath: '/crew/lautstaerke'
      preLoaderRoute: typeof CrewLautstaerkeRouteImport
      parentRoute: typeof CrewRoute
    }
    '/_main/speisekarte': {
      id: '/_main/speisekarte'
      path: '/speisekarte'
      fullPath: '/speisekarte'
      preLoaderRoute: typeof MainSpeisekarteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/plakate': {
      id: '/_main/plakate'
      path: '/plakate'
      fullPath: '/plakate'
      preLoaderRoute: typeof MainPlakateRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/nuclino-sso': {
      id: '/_main/nuclino-sso'
      path: '/nuclino-sso'
      fullPath: '/nuclino-sso'
      preLoaderRoute: typeof MainNuclinoSsoRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/mitgliedsantrag': {
      id: '/_main/mitgliedsantrag'
      path: '/mitgliedsantrag'
      fullPath: '/mitgliedsantrag'
      preLoaderRoute: typeof MainMitgliedsantragRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/logo': {
      id: '/_main/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof MainLogoRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/lineup': {
      id: '/_main/lineup'
      path: '/lineup'
      fullPath: '/lineup'
      preLoaderRoute: typeof MainLineupRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/learn': {
      id: '/_main/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof MainLearnRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/infos': {
      id: '/_main/infos'
      path: '/infos'
      fullPath: '/infos'
      preLoaderRoute: typeof MainInfosRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/events': {
      id: '/_main/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof MainEventsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/booking': {
      id: '/_main/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof MainBookingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/badges': {
      id: '/_main/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof MainBadgesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/angebot': {
      id: '/_main/angebot'
      path: '/angebot'
      fullPath: '/angebot'
      preLoaderRoute: typeof MainAngebotRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/Route': {
      id: '/_main/Route'
      path: '/Route'
      fullPath: '/Route'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$slug': {
      id: '/_main/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof MainSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/crew/lautstaerke/': {
      id: '/crew/lautstaerke/'
      path: '/'
      fullPath: '/crew/lautstaerke/'
      preLoaderRoute: typeof CrewLautstaerkeIndexRouteImport
      parentRoute: typeof CrewLautstaerkeRoute
    }
    '/_main/lineup/': {
      id: '/_main/lineup/'
      path: '/'
      fullPath: '/lineup/'
      preLoaderRoute: typeof MainLineupIndexRouteImport
      parentRoute: typeof MainLineupRoute
    }
    '/crew/lautstaerke/$device': {
      id: '/crew/lautstaerke/$device'
      path: '/$device'
      fullPath: '/crew/lautstaerke/$device'
      preLoaderRoute: typeof CrewLautstaerkeDeviceRouteImport
      parentRoute: typeof CrewLautstaerkeRoute
    }
    '/api/tasks/spotify-listeners': {
      id: '/api/tasks/spotify-listeners'
      path: '/api/tasks/spotify-listeners'
      fullPath: '/api/tasks/spotify-listeners'
      preLoaderRoute: typeof ApiTasksSpotifyListenersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/send-email': {
      id: '/api/tasks/send-email'
      path: '/api/tasks/send-email'
      fullPath: '/api/tasks/send-email'
      preLoaderRoute: typeof ApiTasksSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/nonce-request-invalidate': {
      id: '/api/tasks/nonce-request-invalidate'
      path: '/api/tasks/nonce-request-invalidate'
      fullPath: '/api/tasks/nonce-request-invalidate'
      preLoaderRoute: typeof ApiTasksNonceRequestInvalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/nonce-invalidate': {
      id: '/api/tasks/nonce-invalidate'
      path: '/api/tasks/nonce-invalidate'
      fullPath: '/api/tasks/nonce-invalidate'
      preLoaderRoute: typeof ApiTasksNonceInvalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/instagram-follower': {
      id: '/api/tasks/instagram-follower'
      path: '/api/tasks/instagram-follower'
      fullPath: '/api/tasks/instagram-follower'
      preLoaderRoute: typeof ApiTasksInstagramFollowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/gmail-watch-refresh': {
      id: '/api/tasks/gmail-watch-refresh'
      path: '/api/tasks/gmail-watch-refresh'
      fullPath: '/api/tasks/gmail-watch-refresh'
      preLoaderRoute: typeof ApiTasksGmailWatchRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/gmail-reminder': {
      id: '/api/tasks/gmail-reminder'
      path: '/api/tasks/gmail-reminder'
      fullPath: '/api/tasks/gmail-reminder'
      preLoaderRoute: typeof ApiTasksGmailReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/gmail-notification': {
      id: '/api/tasks/gmail-notification'
      path: '/api/tasks/gmail-notification'
      fullPath: '/api/tasks/gmail-notification'
      preLoaderRoute: typeof ApiTasksGmailNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/facebook-likes': {
      id: '/api/tasks/facebook-likes'
      path: '/api/tasks/facebook-likes'
      fullPath: '/api/tasks/facebook-likes'
      preLoaderRoute: typeof ApiTasksFacebookLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/crew-card-enrolled': {
      id: '/api/tasks/crew-card-enrolled'
      path: '/api/tasks/crew-card-enrolled'
      fullPath: '/api/tasks/crew-card-enrolled'
      preLoaderRoute: typeof ApiTasksCrewCardEnrolledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/create-nonce-request': {
      id: '/api/tasks/create-nonce-request'
      path: '/api/tasks/create-nonce-request'
      fullPath: '/api/tasks/create-nonce-request'
      preLoaderRoute: typeof ApiTasksCreateNonceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/create-membership-application': {
      id: '/api/tasks/create-membership-application'
      path: '/api/tasks/create-membership-application'
      fullPath: '/api/tasks/create-membership-application'
      preLoaderRoute: typeof ApiTasksCreateMembershipApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/create-band-application': {
      id: '/api/tasks/create-band-application'
      path: '/api/tasks/create-band-application'
      fullPath: '/api/tasks/create-band-application'
      preLoaderRoute: typeof ApiTasksCreateBandApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/band-application-distance': {
      id: '/api/tasks/band-application-distance'
      path: '/api/tasks/band-application-distance'
      fullPath: '/api/tasks/band-application-distance'
      preLoaderRoute: typeof ApiTasksBandApplicationDistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/band-application-demo': {
      id: '/api/tasks/band-application-demo'
      path: '/api/tasks/band-application-demo'
      fullPath: '/api/tasks/band-application-demo'
      preLoaderRoute: typeof ApiTasksBandApplicationDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/badge-awarded': {
      id: '/api/tasks/badge-awarded'
      path: '/api/tasks/badge-awarded'
      fullPath: '/api/tasks/badge-awarded'
      preLoaderRoute: typeof ApiTasksBadgeAwardedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/noise/log': {
      id: '/api/noise/log'
      path: '/api/noise/log'
      fullPath: '/api/noise/log'
      preLoaderRoute: typeof ApiNoiseLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kultcash/log': {
      id: '/api/kultcash/log'
      path: '/api/kultcash/log'
      fullPath: '/api/kultcash/log'
      preLoaderRoute: typeof ApiKultcashLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kultcash/lists': {
      id: '/api/kultcash/lists'
      path: '/api/kultcash/lists'
      fullPath: '/api/kultcash/lists'
      preLoaderRoute: typeof ApiKultcashListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kultcash/config': {
      id: '/api/kultcash/config'
      path: '/api/kultcash/config'
      fullPath: '/api/kultcash/config'
      preLoaderRoute: typeof ApiKultcashConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/news/archiv': {
      id: '/_main/news/archiv'
      path: '/news/archiv'
      fullPath: '/news/archiv'
      preLoaderRoute: typeof MainNewsArchivRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/news/$slug': {
      id: '/_main/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof MainNewsSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/mitgliedsantrag_/danke': {
      id: '/_main/mitgliedsantrag_/danke'
      path: '/mitgliedsantrag/danke'
      fullPath: '/mitgliedsantrag/danke'
      preLoaderRoute: typeof MainMitgliedsantragDankeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/lineup/$year': {
      id: '/_main/lineup/$year'
      path: '/$year'
      fullPath: '/lineup/$year'
      preLoaderRoute: typeof MainLineupYearRouteImport
      parentRoute: typeof MainLineupRoute
    }
    '/_main/events_/$id': {
      id: '/_main/events_/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof MainEventsIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/card/$hash': {
      id: '/_main/card/$hash'
      path: '/card/$hash'
      fullPath: '/card/$hash'
      preLoaderRoute: typeof MainCardHashRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/booking_/$applicationType': {
      id: '/_main/booking_/$applicationType'
      path: '/booking/$applicationType'
      fullPath: '/booking/$applicationType'
      preLoaderRoute: typeof MainBookingApplicationTypeRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/spenden/quittung/$id': {
      id: '/api/spenden/quittung/$id'
      path: '/api/spenden/quittung/$id'
      fullPath: '/api/spenden/quittung/$id'
      preLoaderRoute: typeof ApiSpendenQuittungIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/spenden_/quittung/$id': {
      id: '/_main/spenden_/quittung/$id'
      path: '/spenden/quittung/$id'
      fullPath: '/spenden/quittung/$id'
      preLoaderRoute: typeof MainSpendenQuittungIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/lineup/$year_/$slug': {
      id: '/_main/lineup/$year_/$slug'
      path: '/$year/$slug'
      fullPath: '/lineup/$year/$slug'
      preLoaderRoute: typeof MainLineupYearSlugRouteImport
      parentRoute: typeof MainLineupRoute
    }
    '/_main/card/$hash/kult': {
      id: '/_main/card/$hash/kult'
      path: '/kult'
      fullPath: '/card/$hash/kult'
      preLoaderRoute: typeof MainCardHashKultRouteImport
      parentRoute: typeof MainCardHashRoute
    }
    '/_main/card/$hash/crew': {
      id: '/_main/card/$hash/crew'
      path: '/crew'
      fullPath: '/card/$hash/crew'
      preLoaderRoute: typeof MainCardHashCrewRouteImport
      parentRoute: typeof MainCardHashRoute
    }
    '/_main/booking_/$applicationType_/danke': {
      id: '/_main/booking_/$applicationType_/danke'
      path: '/booking/$applicationType/danke'
      fullPath: '/booking/$applicationType/danke'
      preLoaderRoute: typeof MainBookingApplicationTypeDankeRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainLineupRouteChildren {
  MainLineupYearRoute: typeof MainLineupYearRoute
  MainLineupIndexRoute: typeof MainLineupIndexRoute
  MainLineupYearSlugRoute: typeof MainLineupYearSlugRoute
}

const MainLineupRouteChildren: MainLineupRouteChildren = {
  MainLineupYearRoute: MainLineupYearRoute,
  MainLineupIndexRoute: MainLineupIndexRoute,
  MainLineupYearSlugRoute: MainLineupYearSlugRoute,
}

const MainLineupRouteWithChildren = MainLineupRoute._addFileChildren(
  MainLineupRouteChildren,
)

interface MainCardHashRouteChildren {
  MainCardHashCrewRoute: typeof MainCardHashCrewRoute
  MainCardHashKultRoute: typeof MainCardHashKultRoute
}

const MainCardHashRouteChildren: MainCardHashRouteChildren = {
  MainCardHashCrewRoute: MainCardHashCrewRoute,
  MainCardHashKultRoute: MainCardHashKultRoute,
}

const MainCardHashRouteWithChildren = MainCardHashRoute._addFileChildren(
  MainCardHashRouteChildren,
)

interface MainRouteChildren {
  MainSlugRoute: typeof MainSlugRoute
  MainRouteRoute: typeof MainRouteRoute
  MainAngebotRoute: typeof MainAngebotRoute
  MainBadgesRoute: typeof MainBadgesRoute
  MainBookingRoute: typeof MainBookingRoute
  MainEventsRoute: typeof MainEventsRoute
  MainInfosRoute: typeof MainInfosRoute
  MainLearnRoute: typeof MainLearnRoute
  MainLineupRoute: typeof MainLineupRouteWithChildren
  MainLogoRoute: typeof MainLogoRoute
  MainMitgliedsantragRoute: typeof MainMitgliedsantragRoute
  MainNuclinoSsoRoute: typeof MainNuclinoSsoRoute
  MainPlakateRoute: typeof MainPlakateRoute
  MainSpeisekarteRoute: typeof MainSpeisekarteRoute
  MainIndexRoute: typeof MainIndexRoute
  MainBookingApplicationTypeRoute: typeof MainBookingApplicationTypeRoute
  MainCardHashRoute: typeof MainCardHashRouteWithChildren
  MainEventsIdRoute: typeof MainEventsIdRoute
  MainMitgliedsantragDankeRoute: typeof MainMitgliedsantragDankeRoute
  MainNewsSlugRoute: typeof MainNewsSlugRoute
  MainNewsArchivRoute: typeof MainNewsArchivRoute
  MainBookingApplicationTypeDankeRoute: typeof MainBookingApplicationTypeDankeRoute
  MainSpendenQuittungIdRoute: typeof MainSpendenQuittungIdRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainSlugRoute: MainSlugRoute,
  MainRouteRoute: MainRouteRoute,
  MainAngebotRoute: MainAngebotRoute,
  MainBadgesRoute: MainBadgesRoute,
  MainBookingRoute: MainBookingRoute,
  MainEventsRoute: MainEventsRoute,
  MainInfosRoute: MainInfosRoute,
  MainLearnRoute: MainLearnRoute,
  MainLineupRoute: MainLineupRouteWithChildren,
  MainLogoRoute: MainLogoRoute,
  MainMitgliedsantragRoute: MainMitgliedsantragRoute,
  MainNuclinoSsoRoute: MainNuclinoSsoRoute,
  MainPlakateRoute: MainPlakateRoute,
  MainSpeisekarteRoute: MainSpeisekarteRoute,
  MainIndexRoute: MainIndexRoute,
  MainBookingApplicationTypeRoute: MainBookingApplicationTypeRoute,
  MainCardHashRoute: MainCardHashRouteWithChildren,
  MainEventsIdRoute: MainEventsIdRoute,
  MainMitgliedsantragDankeRoute: MainMitgliedsantragDankeRoute,
  MainNewsSlugRoute: MainNewsSlugRoute,
  MainNewsArchivRoute: MainNewsArchivRoute,
  MainBookingApplicationTypeDankeRoute: MainBookingApplicationTypeDankeRoute,
  MainSpendenQuittungIdRoute: MainSpendenQuittungIdRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface CrewLautstaerkeRouteChildren {
  CrewLautstaerkeDeviceRoute: typeof CrewLautstaerkeDeviceRoute
  CrewLautstaerkeIndexRoute: typeof CrewLautstaerkeIndexRoute
}

const CrewLautstaerkeRouteChildren: CrewLautstaerkeRouteChildren = {
  CrewLautstaerkeDeviceRoute: CrewLautstaerkeDeviceRoute,
  CrewLautstaerkeIndexRoute: CrewLautstaerkeIndexRoute,
}

const CrewLautstaerkeRouteWithChildren = CrewLautstaerkeRoute._addFileChildren(
  CrewLautstaerkeRouteChildren,
)

interface CrewRouteChildren {
  CrewLautstaerkeRoute: typeof CrewLautstaerkeRouteWithChildren
  CrewIndexRoute: typeof CrewIndexRoute
}

const CrewRouteChildren: CrewRouteChildren = {
  CrewLautstaerkeRoute: CrewLautstaerkeRouteWithChildren,
  CrewIndexRoute: CrewIndexRoute,
}

const CrewRouteWithChildren = CrewRoute._addFileChildren(CrewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  CrewRoute: CrewRouteWithChildren,
  SamlLoginRoute: SamlLoginRoute,
  SamlLogoutRoute: SamlLogoutRoute,
  ApiKultcashConfigRoute: ApiKultcashConfigRoute,
  ApiKultcashListsRoute: ApiKultcashListsRoute,
  ApiKultcashLogRoute: ApiKultcashLogRoute,
  ApiNoiseLogRoute: ApiNoiseLogRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTasksBadgeAwardedRoute: ApiTasksBadgeAwardedRoute,
  ApiTasksBandApplicationDemoRoute: ApiTasksBandApplicationDemoRoute,
  ApiTasksBandApplicationDistanceRoute: ApiTasksBandApplicationDistanceRoute,
  ApiTasksCreateBandApplicationRoute: ApiTasksCreateBandApplicationRoute,
  ApiTasksCreateMembershipApplicationRoute:
    ApiTasksCreateMembershipApplicationRoute,
  ApiTasksCreateNonceRequestRoute: ApiTasksCreateNonceRequestRoute,
  ApiTasksCrewCardEnrolledRoute: ApiTasksCrewCardEnrolledRoute,
  ApiTasksFacebookLikesRoute: ApiTasksFacebookLikesRoute,
  ApiTasksGmailNotificationRoute: ApiTasksGmailNotificationRoute,
  ApiTasksGmailReminderRoute: ApiTasksGmailReminderRoute,
  ApiTasksGmailWatchRefreshRoute: ApiTasksGmailWatchRefreshRoute,
  ApiTasksInstagramFollowerRoute: ApiTasksInstagramFollowerRoute,
  ApiTasksNonceInvalidateRoute: ApiTasksNonceInvalidateRoute,
  ApiTasksNonceRequestInvalidateRoute: ApiTasksNonceRequestInvalidateRoute,
  ApiTasksSendEmailRoute: ApiTasksSendEmailRoute,
  ApiTasksSpotifyListenersRoute: ApiTasksSpotifyListenersRoute,
  ApiSpendenQuittungIdRoute: ApiSpendenQuittungIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
