name: Deploy

on:
  push:
    branches:
      - remix

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn
      - name: upload sourcemaps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          yarn remix build --sourcemap
          yarn sentry-cli releases new ${{ github.sha }} --org ${{ secrets.SENTRY_ORG }} --project ${{ secrets.SENTRY_PROJECT }}
          yarn sentry-upload-sourcemaps --org ${{ secrets.SENTRY_ORG }} --project ${{ secrets.SENTRY_PROJECT }} --release ${{ github.sha }}
          yarn sentry-cli releases finalize ${{ github.sha }}
      - name: deploy
        run: yarn vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
