name: Deploy

on:
  push:
    branches:
      - remix

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn install
      - name: deploy
        run: yarn vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
